drop extension if exists "pg_net";

create type "public"."ai_trend_signal" as enum ('EXPANSION', 'CONTRACTION', 'OPTIMIZATION', 'OVERCAPACITY', 'FLAT');

create type "public"."company_archetype" as enum ('HYPERSCALER', 'FOUNDRY', 'EQUIPMENT', 'MEMORY', 'SOFTWARE');

create type "public"."sync_job_type" as enum ('DAILY', 'M5', 'OPTIONS', 'SHORT_VOLUME', 'SENTIMENT', 'EVENTS', 'SECTOR_ROTATION');

create sequence "public"."ticker_dependencies_id_seq";


  create table "public"."cboe_options_volume" (
    "ticker" integer not null,
    "timestamp" integer not null,
    "volume" integer
      );


alter table "public"."cboe_options_volume" enable row level security;


  create table "public"."daily_candles" (
    "ticker" integer not null,
    "timestamp" integer not null,
    "open" real,
    "high" real,
    "low" real,
    "close" real,
    "volume" integer,
    "vwap" real,
    "trades" integer
      );


alter table "public"."daily_candles" enable row level security;


  create table "public"."eodhd_sync_queue" (
    "ticker" character varying(50) not null,
    "last_sync_at" timestamp with time zone
      );


alter table "public"."eodhd_sync_queue" enable row level security;


  create table "public"."event_calendar" (
    "id" bigint generated by default as identity not null,
    "ticker_id" bigint not null,
    "ticker_name" character varying(10) not null,
    "event_typ" character varying(50) not null,
    "event_datum" date not null,
    "beschreibung" text,
    "status" character varying(50) default 'SCHEDULED'::character varying,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "updated_at" timestamp with time zone not null default timezone('utc'::text, now())
      );


alter table "public"."event_calendar" enable row level security;


  create table "public"."finra_short_volume" (
    "ticker" integer not null,
    "timestamp" integer not null,
    "short_volume" bigint,
    "total_volume" bigint
      );


alter table "public"."finra_short_volume" enable row level security;


  create table "public"."fx_rates_daily" (
    "observation_date" date not null,
    "currency_pair" character varying(10) not null,
    "rate" numeric,
    "created_at" timestamp with time zone default timezone('utc'::text, now())
      );


alter table "public"."fx_rates_daily" enable row level security;


  create table "public"."global_macro_indicator_definition" (
    "id" uuid not null default gen_random_uuid(),
    "series_id" character varying(50) not null,
    "region" character varying(50) not null,
    "currency" character varying(10) not null,
    "description" text,
    "created_at" timestamp with time zone default timezone('utc'::text, now())
      );


alter table "public"."global_macro_indicator_definition" enable row level security;


  create table "public"."global_macro_indicator_values" (
    "indicator_id" uuid not null,
    "observation_date" date not null,
    "raw_value" numeric,
    "created_at" timestamp with time zone default timezone('utc'::text, now())
      );


alter table "public"."global_macro_indicator_values" enable row level security;


  create table "public"."labor_market_data_points" (
    "id" bigint generated always as identity not null,
    "series_id" character varying(50),
    "data_period" date not null,
    "release_date" date not null,
    "value" numeric not null,
    "is_preliminary" boolean default true,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."labor_market_data_points" enable row level security;


  create table "public"."labor_market_series" (
    "id" character varying(50) not null,
    "name" character varying(100) not null,
    "category" character varying(50) not null,
    "frequency" character varying(20) not null
      );


alter table "public"."labor_market_series" enable row level security;


  create table "public"."m5_candles" (
    "ticker" integer not null,
    "timestamp" integer not null,
    "open" real,
    "high" real,
    "low" real,
    "close" real,
    "volume" integer,
    "vwap" real,
    "trades" integer
      );


alter table "public"."m5_candles" enable row level security;


  create table "public"."macro_indicator_definition" (
    "id" integer generated always as identity not null,
    "series_id" character varying(50) not null,
    "source" character varying(50) default 'FRED'::character varying,
    "name" character varying(255) not null,
    "frequency" character varying(20) not null,
    "beschreibung" text
      );


alter table "public"."macro_indicator_definition" enable row level security;


  create table "public"."macro_indicator_values" (
    "indicator_id" integer not null,
    "observation_date" date not null,
    "value" numeric(20,4) not null,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now())
      );


alter table "public"."macro_indicator_values" enable row level security;


  create table "public"."macro_liquidity" (
    "observation_date" date not null,
    "tga_balance" numeric,
    "rrp_balance" numeric,
    "fed_balance" numeric,
    "btfp_balance" numeric,
    "updated_at" timestamp with time zone default timezone('utc'::text, now()),
    "bank_reserves_fed" numeric,
    "sofr_rate" numeric
      );


alter table "public"."macro_liquidity" enable row level security;


  create table "public"."macro_news_feed" (
    "article_link" text not null,
    "published_at" timestamp with time zone not null,
    "title" text not null,
    "tags" jsonb,
    "sentiment_polarity" numeric,
    "inserted_at" timestamp with time zone default timezone('utc'::text, now())
      );


alter table "public"."macro_news_feed" enable row level security;


  create table "public"."market_sentiment_daily" (
    "observation_date" date not null,
    "ticker" character varying(50) not null,
    "article_count" integer default 0,
    "normalized_score" numeric,
    "updated_at" timestamp with time zone default timezone('utc'::text, now())
      );


alter table "public"."market_sentiment_daily" enable row level security;


  create table "public"."option_chain_snapshots" (
    "id" bigint generated always as identity not null,
    "scraped_at" timestamp with time zone not null default now(),
    "ticker" integer not null,
    "ticker_symbol" character varying(10) not null,
    "contract_id" character varying(30) not null,
    "expiration_date" date not null,
    "option_type" character varying(4) not null,
    "strike" numeric(10,2) not null,
    "volume_oi_ratio" numeric(12,4) not null default 0.0000,
    "volume" bigint default 0,
    "open_interest" bigint default 0,
    "last_price" numeric(10,2) default 0.00
      );


alter table "public"."option_chain_snapshots" enable row level security;


  create table "public"."option_contract_bars" (
    "id" bigint generated always as identity not null,
    "ticker" integer not null,
    "contract_id" character varying(30) not null,
    "bar_timestamp" timestamp with time zone not null,
    "volume" bigint not null default 0,
    "open" numeric(10,4) not null,
    "high" numeric(10,4) not null,
    "low" numeric(10,4) not null,
    "close" numeric(10,4) not null,
    "vwap" numeric(10,4) not null,
    "trade_count" bigint not null default 0,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."option_contract_bars" enable row level security;


  create table "public"."regulation_alerts" (
    "document_number" character varying(100) not null,
    "publication_date" date not null,
    "title" text not null,
    "pdf_url" text,
    "created_at" timestamp with time zone default timezone('utc'::text, now()),
    "abstract" text
      );


alter table "public"."regulation_alerts" enable row level security;


  create table "public"."reserve_requirements" (
    "effective_date" date not null,
    "ratio_percent" numeric not null,
    "document_number" character varying(100),
    "created_at" timestamp with time zone default timezone('utc'::text, now())
      );


alter table "public"."reserve_requirements" enable row level security;


  create table "public"."sec_ai_signals" (
    "id" uuid not null default gen_random_uuid(),
    "filing_id" uuid not null,
    "ticker" character varying(10) not null,
    "signal_category" character varying(100) not null,
    "trend" public.ai_trend_signal not null,
    "extracted_quote" text not null,
    "ai_reasoning" text,
    "created_at" timestamp with time zone default CURRENT_TIMESTAMP,
    "filing_date" date
      );


alter table "public"."sec_ai_signals" enable row level security;


  create table "public"."sec_companies" (
    "ticker" character varying(10) not null,
    "cik" character varying(10),
    "company_name" character varying(255),
    "is_foreign_issuer" boolean default false,
    "is_active" boolean default true,
    "created_at" timestamp with time zone default CURRENT_TIMESTAMP,
    "updated_at" timestamp with time zone default CURRENT_TIMESTAMP,
    "archetype" public.company_archetype
      );


alter table "public"."sec_companies" enable row level security;


  create table "public"."sec_companies_keywords" (
    "id" uuid not null default gen_random_uuid(),
    "ticker" character varying(10),
    "metric_name" character varying(100) not null,
    "keyword" character varying(255) not null,
    "is_active" boolean default true,
    "created_at" timestamp with time zone default CURRENT_TIMESTAMP
      );


alter table "public"."sec_companies_keywords" enable row level security;


  create table "public"."sec_fmp_fundamentals" (
    "id" uuid not null default gen_random_uuid(),
    "ticker" character varying(10) not null,
    "fiscal_year" integer not null,
    "period" character varying(10) not null,
    "filing_date" date not null,
    "capex_actual" numeric,
    "revenue" numeric,
    "r_and_d" numeric,
    "inventory_value" numeric,
    "inventory_turnover" numeric,
    "days_sales_outstanding" numeric,
    "deferred_revenue" numeric,
    "gross_profit_margin" numeric,
    "operating_cash_flow" numeric,
    "free_cash_flow" numeric,
    "created_at" timestamp with time zone default CURRENT_TIMESTAMP
      );


alter table "public"."sec_fmp_fundamentals" enable row level security;


  create table "public"."sec_raw_filings" (
    "id" uuid not null default gen_random_uuid(),
    "ticker" character varying(10),
    "form_type" character varying(20) not null,
    "filing_date" date not null,
    "accession_number" character varying(255) not null,
    "raw_content" text not null,
    "created_at" timestamp with time zone default CURRENT_TIMESTAMP
      );


alter table "public"."sec_raw_filings" enable row level security;


  create table "public"."sector_rotation_log" (
    "id" bigint generated by default as identity not null,
    "datum" date not null,
    "ticker_id" bigint not null,
    "ticker_name" character varying(10) not null,
    "phase" character varying(50) not null,
    "adj_score" numeric(5,2) not null,
    "raw_score" numeric(5,2) not null,
    "rsi50" numeric(5,2) not null,
    "velocity" numeric(8,4) not null,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now())
      );


alter table "public"."sector_rotation_log" enable row level security;


  create table "public"."ticker" (
    "id" integer generated always as identity not null,
    "name" text not null,
    "company" text not null,
    "sector" text,
    "ticker_typ_id" integer
      );


alter table "public"."ticker" enable row level security;


  create table "public"."ticker_data_config" (
    "ticker_id" integer not null,
    "sync_type" public.sync_job_type not null,
    "is_active" boolean not null default true,
    "created_at" timestamp with time zone default timezone('utc'::text, now())
      );


alter table "public"."ticker_data_config" enable row level security;


  create table "public"."ticker_dependencies" (
    "id" integer not null default nextval('public.ticker_dependencies_id_seq'::regclass),
    "target_ticker_id" integer,
    "macro_ticker_id" integer,
    "dependency_type" character varying(50),
    "created_at" timestamp with time zone default now()
      );


alter table "public"."ticker_dependencies" enable row level security;


  create table "public"."ticker_typ" (
    "id" integer generated always as identity not null,
    "name" text not null
      );


alter table "public"."ticker_typ" enable row level security;


  create table "public"."treasury_auctions" (
    "cusip" character varying(50) not null,
    "auction_date" date not null,
    "issue_date" date,
    "maturity_date" date,
    "security_type" character varying(50) not null,
    "security_term" character varying(50) not null,
    "bid_to_cover_ratio" numeric,
    "high_yield" numeric,
    "total_tendered" numeric,
    "total_accepted" numeric,
    "updated_at" timestamp with time zone default timezone('utc'::text, now()),
    "offering_amount" numeric,
    "primary_dealer_accepted" numeric,
    "direct_bidder_accepted" numeric,
    "indirect_bidder_accepted" numeric
      );


alter table "public"."treasury_auctions" enable row level security;


  create table "public"."treasury_qra_estimates" (
    "target_quarter" character varying(10) not null,
    "release_date" date not null,
    "estimated_net_borrowing" numeric,
    "estimated_tga_balance" numeric,
    "updated_at" timestamp with time zone default timezone('utc'::text, now())
      );


alter table "public"."treasury_qra_estimates" enable row level security;

alter sequence "public"."ticker_dependencies_id_seq" owned by "public"."ticker_dependencies"."id";

CREATE UNIQUE INDEX cboe_options_volume_pkey ON public.cboe_options_volume USING btree (ticker, "timestamp");

CREATE UNIQUE INDEX daily_candles_pkey ON public.daily_candles USING btree (ticker, "timestamp");

CREATE UNIQUE INDEX eodhd_sync_queue_pkey ON public.eodhd_sync_queue USING btree (ticker);

CREATE UNIQUE INDEX event_calendar_pkey ON public.event_calendar USING btree (id);

CREATE UNIQUE INDEX finra_short_volume_pkey ON public.finra_short_volume USING btree (ticker, "timestamp");

CREATE UNIQUE INDEX fx_rates_daily_pkey ON public.fx_rates_daily USING btree (observation_date, currency_pair);

CREATE UNIQUE INDEX global_macro_indicator_definition_pkey ON public.global_macro_indicator_definition USING btree (id);

CREATE UNIQUE INDEX global_macro_indicator_definition_series_id_key ON public.global_macro_indicator_definition USING btree (series_id);

CREATE UNIQUE INDEX global_macro_indicator_values_pkey ON public.global_macro_indicator_values USING btree (indicator_id, observation_date);

CREATE INDEX idx_ai_signals_ticker_trend ON public.sec_ai_signals USING btree (ticker, trend);

CREATE INDEX idx_contract_bars_lookup ON public.option_contract_bars USING btree (contract_id, bar_timestamp);

CREATE INDEX idx_event_calendar_datum ON public.event_calendar USING btree (event_datum);

CREATE INDEX idx_event_calendar_ticker ON public.event_calendar USING btree (ticker_name);

CREATE INDEX idx_fmp_ticker_date ON public.sec_fmp_fundamentals USING btree (ticker, filing_date DESC);

CREATE INDEX idx_fx_rates_date ON public.fx_rates_daily USING btree (observation_date);

CREATE INDEX idx_global_macro_date ON public.global_macro_indicator_values USING btree (observation_date);

CREATE INDEX idx_labor_market_data_lookup ON public.labor_market_data_points USING btree (series_id, data_period);

CREATE INDEX idx_macro_values_date ON public.macro_indicator_values USING btree (observation_date DESC);

CREATE INDEX idx_option_chain_ratio_trigger ON public.option_chain_snapshots USING btree (volume_oi_ratio) WHERE (volume_oi_ratio > 1.0);

CREATE INDEX idx_option_chain_ticker_id_time ON public.option_chain_snapshots USING btree (ticker, scraped_at DESC);

CREATE INDEX idx_sec_keywords_ticker ON public.sec_companies_keywords USING btree (ticker);

CREATE INDEX idx_sec_raw_ticker ON public.sec_raw_filings USING btree (ticker);

CREATE INDEX idx_sector_log_datum ON public.sector_rotation_log USING btree (datum);

CREATE INDEX idx_sector_log_ticker ON public.sector_rotation_log USING btree (ticker_name);

CREATE INDEX idx_ticker_config_sync_type ON public.ticker_data_config USING btree (sync_type) WHERE (is_active = true);

CREATE UNIQUE INDEX labor_market_data_points_pkey ON public.labor_market_data_points USING btree (id);

CREATE UNIQUE INDEX labor_market_data_points_series_period_key ON public.labor_market_data_points USING btree (series_id, data_period);

CREATE UNIQUE INDEX labor_market_series_pkey ON public.labor_market_series USING btree (id);

CREATE UNIQUE INDEX m5_candles_pkey ON public.m5_candles USING btree (ticker, "timestamp");

CREATE UNIQUE INDEX macro_indicator_definition_pkey ON public.macro_indicator_definition USING btree (id);

CREATE UNIQUE INDEX macro_indicator_values_pkey ON public.macro_indicator_values USING btree (indicator_id, observation_date);

CREATE UNIQUE INDEX macro_liquidity_pkey ON public.macro_liquidity USING btree (observation_date);

CREATE UNIQUE INDEX macro_news_feed_pkey ON public.macro_news_feed USING btree (article_link);

CREATE UNIQUE INDEX market_sentiment_daily_pkey ON public.market_sentiment_daily USING btree (observation_date, ticker);

CREATE UNIQUE INDEX option_chain_snapshots_pkey ON public.option_chain_snapshots USING btree (id);

CREATE UNIQUE INDEX option_contract_bars_pkey ON public.option_contract_bars USING btree (id);

CREATE UNIQUE INDEX regulation_alerts_pkey ON public.regulation_alerts USING btree (document_number);

CREATE UNIQUE INDEX reserve_requirements_pkey ON public.reserve_requirements USING btree (effective_date);

CREATE UNIQUE INDEX sec_ai_signals_pkey ON public.sec_ai_signals USING btree (id);

CREATE UNIQUE INDEX sec_companies_keywords_pkey ON public.sec_companies_keywords USING btree (id);

CREATE UNIQUE INDEX sec_companies_keywords_ticker_metric_name_keyword_key ON public.sec_companies_keywords USING btree (ticker, metric_name, keyword);

CREATE UNIQUE INDEX sec_companies_pkey ON public.sec_companies USING btree (ticker);

CREATE UNIQUE INDEX sec_fmp_fundamentals_pkey ON public.sec_fmp_fundamentals USING btree (id);

CREATE UNIQUE INDEX sec_raw_filings_accession_number_key ON public.sec_raw_filings USING btree (accession_number);

CREATE UNIQUE INDEX sec_raw_filings_pkey ON public.sec_raw_filings USING btree (id);

CREATE UNIQUE INDEX sector_rotation_log_pkey ON public.sector_rotation_log USING btree (id);

CREATE UNIQUE INDEX ticker_data_config_pkey ON public.ticker_data_config USING btree (ticker_id, sync_type);

CREATE UNIQUE INDEX ticker_dependencies_pkey ON public.ticker_dependencies USING btree (id);

CREATE UNIQUE INDEX ticker_pkey ON public.ticker USING btree (id);

CREATE UNIQUE INDEX ticker_typ_name_key ON public.ticker_typ USING btree (name);

CREATE UNIQUE INDEX ticker_typ_pkey ON public.ticker_typ USING btree (id);

CREATE UNIQUE INDEX treasury_auctions_pkey ON public.treasury_auctions USING btree (cusip);

CREATE UNIQUE INDEX treasury_qra_estimates_pkey ON public.treasury_qra_estimates USING btree (target_quarter, release_date);

CREATE UNIQUE INDEX unique_chain_snapshot_entry ON public.option_chain_snapshots USING btree (contract_id, scraped_at);

CREATE UNIQUE INDEX unique_contract_bar_entry ON public.option_contract_bars USING btree (contract_id, bar_timestamp);

CREATE UNIQUE INDEX unique_daily_sector_log ON public.sector_rotation_log USING btree (datum, ticker_id);

CREATE UNIQUE INDEX unique_series_id ON public.macro_indicator_definition USING btree (series_id);

CREATE UNIQUE INDEX unique_ticker_event ON public.event_calendar USING btree (ticker_id, event_typ, event_datum);

alter table "public"."cboe_options_volume" add constraint "cboe_options_volume_pkey" PRIMARY KEY using index "cboe_options_volume_pkey";

alter table "public"."daily_candles" add constraint "daily_candles_pkey" PRIMARY KEY using index "daily_candles_pkey";

alter table "public"."eodhd_sync_queue" add constraint "eodhd_sync_queue_pkey" PRIMARY KEY using index "eodhd_sync_queue_pkey";

alter table "public"."event_calendar" add constraint "event_calendar_pkey" PRIMARY KEY using index "event_calendar_pkey";

alter table "public"."finra_short_volume" add constraint "finra_short_volume_pkey" PRIMARY KEY using index "finra_short_volume_pkey";

alter table "public"."fx_rates_daily" add constraint "fx_rates_daily_pkey" PRIMARY KEY using index "fx_rates_daily_pkey";

alter table "public"."global_macro_indicator_definition" add constraint "global_macro_indicator_definition_pkey" PRIMARY KEY using index "global_macro_indicator_definition_pkey";

alter table "public"."global_macro_indicator_values" add constraint "global_macro_indicator_values_pkey" PRIMARY KEY using index "global_macro_indicator_values_pkey";

alter table "public"."labor_market_data_points" add constraint "labor_market_data_points_pkey" PRIMARY KEY using index "labor_market_data_points_pkey";

alter table "public"."labor_market_series" add constraint "labor_market_series_pkey" PRIMARY KEY using index "labor_market_series_pkey";

alter table "public"."m5_candles" add constraint "m5_candles_pkey" PRIMARY KEY using index "m5_candles_pkey";

alter table "public"."macro_indicator_definition" add constraint "macro_indicator_definition_pkey" PRIMARY KEY using index "macro_indicator_definition_pkey";

alter table "public"."macro_indicator_values" add constraint "macro_indicator_values_pkey" PRIMARY KEY using index "macro_indicator_values_pkey";

alter table "public"."macro_liquidity" add constraint "macro_liquidity_pkey" PRIMARY KEY using index "macro_liquidity_pkey";

alter table "public"."macro_news_feed" add constraint "macro_news_feed_pkey" PRIMARY KEY using index "macro_news_feed_pkey";

alter table "public"."market_sentiment_daily" add constraint "market_sentiment_daily_pkey" PRIMARY KEY using index "market_sentiment_daily_pkey";

alter table "public"."option_chain_snapshots" add constraint "option_chain_snapshots_pkey" PRIMARY KEY using index "option_chain_snapshots_pkey";

alter table "public"."option_contract_bars" add constraint "option_contract_bars_pkey" PRIMARY KEY using index "option_contract_bars_pkey";

alter table "public"."regulation_alerts" add constraint "regulation_alerts_pkey" PRIMARY KEY using index "regulation_alerts_pkey";

alter table "public"."reserve_requirements" add constraint "reserve_requirements_pkey" PRIMARY KEY using index "reserve_requirements_pkey";

alter table "public"."sec_ai_signals" add constraint "sec_ai_signals_pkey" PRIMARY KEY using index "sec_ai_signals_pkey";

alter table "public"."sec_companies" add constraint "sec_companies_pkey" PRIMARY KEY using index "sec_companies_pkey";

alter table "public"."sec_companies_keywords" add constraint "sec_companies_keywords_pkey" PRIMARY KEY using index "sec_companies_keywords_pkey";

alter table "public"."sec_fmp_fundamentals" add constraint "sec_fmp_fundamentals_pkey" PRIMARY KEY using index "sec_fmp_fundamentals_pkey";

alter table "public"."sec_raw_filings" add constraint "sec_raw_filings_pkey" PRIMARY KEY using index "sec_raw_filings_pkey";

alter table "public"."sector_rotation_log" add constraint "sector_rotation_log_pkey" PRIMARY KEY using index "sector_rotation_log_pkey";

alter table "public"."ticker" add constraint "ticker_pkey" PRIMARY KEY using index "ticker_pkey";

alter table "public"."ticker_data_config" add constraint "ticker_data_config_pkey" PRIMARY KEY using index "ticker_data_config_pkey";

alter table "public"."ticker_dependencies" add constraint "ticker_dependencies_pkey" PRIMARY KEY using index "ticker_dependencies_pkey";

alter table "public"."ticker_typ" add constraint "ticker_typ_pkey" PRIMARY KEY using index "ticker_typ_pkey";

alter table "public"."treasury_auctions" add constraint "treasury_auctions_pkey" PRIMARY KEY using index "treasury_auctions_pkey";

alter table "public"."treasury_qra_estimates" add constraint "treasury_qra_estimates_pkey" PRIMARY KEY using index "treasury_qra_estimates_pkey";

alter table "public"."cboe_options_volume" add constraint "fk_cboe_options_volume_ticker" FOREIGN KEY (ticker) REFERENCES public.ticker(id) ON DELETE CASCADE not valid;

alter table "public"."cboe_options_volume" validate constraint "fk_cboe_options_volume_ticker";

alter table "public"."daily_candles" add constraint "fk_daily_candles_ticker" FOREIGN KEY (ticker) REFERENCES public.ticker(id) ON DELETE CASCADE not valid;

alter table "public"."daily_candles" validate constraint "fk_daily_candles_ticker";

alter table "public"."event_calendar" add constraint "event_calendar_ticker_id_fkey" FOREIGN KEY (ticker_id) REFERENCES public.ticker(id) ON DELETE CASCADE not valid;

alter table "public"."event_calendar" validate constraint "event_calendar_ticker_id_fkey";

alter table "public"."event_calendar" add constraint "unique_ticker_event" UNIQUE using index "unique_ticker_event";

alter table "public"."finra_short_volume" add constraint "fk_finra_short_volume_ticker" FOREIGN KEY (ticker) REFERENCES public.ticker(id) ON DELETE CASCADE not valid;

alter table "public"."finra_short_volume" validate constraint "fk_finra_short_volume_ticker";

alter table "public"."global_macro_indicator_definition" add constraint "global_macro_indicator_definition_series_id_key" UNIQUE using index "global_macro_indicator_definition_series_id_key";

alter table "public"."global_macro_indicator_values" add constraint "global_macro_indicator_values_indicator_id_fkey" FOREIGN KEY (indicator_id) REFERENCES public.global_macro_indicator_definition(id) ON DELETE CASCADE not valid;

alter table "public"."global_macro_indicator_values" validate constraint "global_macro_indicator_values_indicator_id_fkey";

alter table "public"."labor_market_data_points" add constraint "labor_market_data_points_series_id_fkey" FOREIGN KEY (series_id) REFERENCES public.labor_market_series(id) ON DELETE CASCADE not valid;

alter table "public"."labor_market_data_points" validate constraint "labor_market_data_points_series_id_fkey";

alter table "public"."labor_market_data_points" add constraint "labor_market_data_points_series_period_key" UNIQUE using index "labor_market_data_points_series_period_key";

alter table "public"."m5_candles" add constraint "fk_m5_candles_ticker" FOREIGN KEY (ticker) REFERENCES public.ticker(id) ON DELETE CASCADE not valid;

alter table "public"."m5_candles" validate constraint "fk_m5_candles_ticker";

alter table "public"."macro_indicator_definition" add constraint "unique_series_id" UNIQUE using index "unique_series_id";

alter table "public"."macro_indicator_values" add constraint "fk_macro_values_indicator" FOREIGN KEY (indicator_id) REFERENCES public.macro_indicator_definition(id) ON DELETE CASCADE not valid;

alter table "public"."macro_indicator_values" validate constraint "fk_macro_values_indicator";

alter table "public"."option_chain_snapshots" add constraint "fk_option_chain_ticker" FOREIGN KEY (ticker) REFERENCES public.ticker(id) ON DELETE CASCADE not valid;

alter table "public"."option_chain_snapshots" validate constraint "fk_option_chain_ticker";

alter table "public"."option_chain_snapshots" add constraint "option_chain_snapshots_type_check" CHECK (((option_type)::text = ANY (ARRAY['CALL'::text, 'PUT'::text]))) not valid;

alter table "public"."option_chain_snapshots" validate constraint "option_chain_snapshots_type_check";

alter table "public"."option_chain_snapshots" add constraint "unique_chain_snapshot_entry" UNIQUE using index "unique_chain_snapshot_entry";

alter table "public"."option_contract_bars" add constraint "fk_option_contract_bars_ticker" FOREIGN KEY (ticker) REFERENCES public.ticker(id) ON DELETE CASCADE not valid;

alter table "public"."option_contract_bars" validate constraint "fk_option_contract_bars_ticker";

alter table "public"."option_contract_bars" add constraint "unique_contract_bar_entry" UNIQUE using index "unique_contract_bar_entry";

alter table "public"."sec_ai_signals" add constraint "sec_ai_signals_filing_id_fkey" FOREIGN KEY (filing_id) REFERENCES public.sec_raw_filings(id) ON DELETE CASCADE not valid;

alter table "public"."sec_ai_signals" validate constraint "sec_ai_signals_filing_id_fkey";

alter table "public"."sec_ai_signals" add constraint "sec_ai_signals_ticker_fkey" FOREIGN KEY (ticker) REFERENCES public.sec_companies(ticker) ON DELETE CASCADE not valid;

alter table "public"."sec_ai_signals" validate constraint "sec_ai_signals_ticker_fkey";

alter table "public"."sec_companies_keywords" add constraint "sec_companies_keywords_ticker_fkey" FOREIGN KEY (ticker) REFERENCES public.sec_companies(ticker) ON DELETE CASCADE not valid;

alter table "public"."sec_companies_keywords" validate constraint "sec_companies_keywords_ticker_fkey";

alter table "public"."sec_companies_keywords" add constraint "sec_companies_keywords_ticker_metric_name_keyword_key" UNIQUE using index "sec_companies_keywords_ticker_metric_name_keyword_key";

alter table "public"."sec_fmp_fundamentals" add constraint "sec_fmp_fundamentals_ticker_fkey" FOREIGN KEY (ticker) REFERENCES public.sec_companies(ticker) ON DELETE CASCADE not valid;

alter table "public"."sec_fmp_fundamentals" validate constraint "sec_fmp_fundamentals_ticker_fkey";

alter table "public"."sec_raw_filings" add constraint "sec_raw_filings_accession_number_key" UNIQUE using index "sec_raw_filings_accession_number_key";

alter table "public"."sec_raw_filings" add constraint "sec_raw_filings_ticker_fkey" FOREIGN KEY (ticker) REFERENCES public.sec_companies(ticker) ON DELETE CASCADE not valid;

alter table "public"."sec_raw_filings" validate constraint "sec_raw_filings_ticker_fkey";

alter table "public"."sector_rotation_log" add constraint "sector_rotation_log_ticker_id_fkey" FOREIGN KEY (ticker_id) REFERENCES public.ticker(id) ON DELETE CASCADE not valid;

alter table "public"."sector_rotation_log" validate constraint "sector_rotation_log_ticker_id_fkey";

alter table "public"."sector_rotation_log" add constraint "unique_daily_sector_log" UNIQUE using index "unique_daily_sector_log";

alter table "public"."ticker" add constraint "ticker_ticker_typ_id_fkey" FOREIGN KEY (ticker_typ_id) REFERENCES public.ticker_typ(id) ON DELETE SET NULL not valid;

alter table "public"."ticker" validate constraint "ticker_ticker_typ_id_fkey";

alter table "public"."ticker_data_config" add constraint "ticker_data_config_ticker_id_fkey" FOREIGN KEY (ticker_id) REFERENCES public.ticker(id) ON DELETE CASCADE not valid;

alter table "public"."ticker_data_config" validate constraint "ticker_data_config_ticker_id_fkey";

alter table "public"."ticker_dependencies" add constraint "ticker_dependencies_macro_ticker_id_fkey" FOREIGN KEY (macro_ticker_id) REFERENCES public.ticker(id) ON DELETE CASCADE not valid;

alter table "public"."ticker_dependencies" validate constraint "ticker_dependencies_macro_ticker_id_fkey";

alter table "public"."ticker_dependencies" add constraint "ticker_dependencies_target_ticker_id_fkey" FOREIGN KEY (target_ticker_id) REFERENCES public.ticker(id) ON DELETE CASCADE not valid;

alter table "public"."ticker_dependencies" validate constraint "ticker_dependencies_target_ticker_id_fkey";

alter table "public"."ticker_typ" add constraint "ticker_typ_name_key" UNIQUE using index "ticker_typ_name_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.get_missing_sentiment_dates(target_ticker text, start_date date, exclude_weekends boolean)
 RETURNS TABLE(missing_date date)
 LANGUAGE plpgsql
AS $function$
BEGIN
  RETURN QUERY
  WITH date_series AS (
    -- Erstellt den perfekten Kalender vom Startdatum bis heute
    SELECT generate_series(start_date, CURRENT_DATE, '1 day'::interval)::date AS gs_date
  ),
  filtered_series AS (
    -- Filtert Wochenenden heraus, wenn exclude_weekends TRUE ist (ISODOW 6=Sa, 7=So)
    SELECT gs_date
    FROM date_series
    WHERE (exclude_weekends = false) OR (EXTRACT(ISODOW FROM gs_date) < 6)
  )
  -- Gleicht den perfekten Kalender mit deiner Tabelle ab und gibt nur die Lücken zurück
  SELECT f.gs_date
  FROM filtered_series f
  LEFT JOIN public.market_sentiment_daily m
    ON m.observation_date = f.gs_date AND m.ticker = target_ticker
  WHERE m.observation_date IS NULL
  ORDER BY f.gs_date ASC;
END;
$function$
;

create or replace view "public"."labor_market_divergence_matrix" as  WITH adp_raw AS (
         SELECT labor_market_data_points.data_period,
            labor_market_data_points.value AS adp_level
           FROM public.labor_market_data_points
          WHERE ((labor_market_data_points.series_id)::text = 'ADPMNUSNERSA'::text)
        ), adp_mom AS (
         SELECT adp_raw.data_period,
            (adp_raw.adp_level - lag(adp_raw.adp_level) OVER (ORDER BY adp_raw.data_period)) AS adp_new_jobs
           FROM adp_raw
        ), nfp_raw AS (
         SELECT labor_market_data_points.data_period,
            labor_market_data_points.value AS nfp_level_k,
            labor_market_data_points.is_preliminary
           FROM public.labor_market_data_points
          WHERE ((labor_market_data_points.series_id)::text = 'PAYEMS'::text)
        ), nfp_mom AS (
         SELECT nfp_raw.data_period,
            nfp_raw.is_preliminary,
            ((nfp_raw.nfp_level_k - lag(nfp_raw.nfp_level_k) OVER (ORDER BY nfp_raw.data_period)) * (1000)::numeric) AS nfp_new_jobs
           FROM nfp_raw
        ), unrate AS (
         SELECT labor_market_data_points.data_period,
            labor_market_data_points.value AS unrate_value
           FROM public.labor_market_data_points
          WHERE ((labor_market_data_points.series_id)::text = 'UNRATE'::text)
        ), icsa_monthly AS (
         SELECT (date_trunc('month'::text, (labor_market_data_points.data_period)::timestamp with time zone))::date AS data_period,
            round(avg(labor_market_data_points.value)) AS weekly_claims_avg
           FROM public.labor_market_data_points
          WHERE ((labor_market_data_points.series_id)::text = 'ICSA'::text)
          GROUP BY ((date_trunc('month'::text, (labor_market_data_points.data_period)::timestamp with time zone))::date)
        )
 SELECT nfp_mom.data_period AS period,
    adp_mom.adp_new_jobs,
    nfp_mom.nfp_new_jobs AS nfp_preliminary,
    (nfp_mom.nfp_new_jobs - adp_mom.adp_new_jobs) AS divergence_raw,
    unrate.unrate_value,
    icsa_monthly.weekly_claims_avg,
    nfp_mom.is_preliminary
   FROM (((nfp_mom
     LEFT JOIN adp_mom ON ((nfp_mom.data_period = adp_mom.data_period)))
     LEFT JOIN unrate ON ((nfp_mom.data_period = unrate.data_period)))
     LEFT JOIN icsa_monthly ON ((nfp_mom.data_period = icsa_monthly.data_period)))
  ORDER BY nfp_mom.data_period DESC;


create or replace view "public"."vw_treasury_liquidity_mix" as  SELECT issue_date AS observation_date,
    sum(
        CASE
            WHEN ((security_type)::text = 'Bill'::text) THEN total_accepted
            ELSE (0)::numeric
        END) AS tbill_amount,
    sum(
        CASE
            WHEN ((security_type)::text = ANY (ARRAY[('Note'::character varying)::text, ('Bond'::character varying)::text])) THEN total_accepted
            ELSE (0)::numeric
        END) AS coupon_amount,
    sum(total_accepted) AS total_issuance,
        CASE
            WHEN (sum(total_accepted) > (0)::numeric) THEN round(((sum(
            CASE
                WHEN ((security_type)::text = 'Bill'::text) THEN total_accepted
                ELSE (0)::numeric
            END) / sum(total_accepted)) * (100)::numeric), 2)
            ELSE 0.00
        END AS tbill_ratio_percent
   FROM public.treasury_auctions
  WHERE (issue_date IS NOT NULL)
  GROUP BY issue_date
  ORDER BY issue_date DESC;


create or replace view "public"."vw_us_liquidity_score" as  SELECT dates.observation_date,
    walcl.value AS fed_assets,
    tga.value AS tga_balance,
    rrp.value AS rrp_balance,
    sofr.value AS sofr_rate,
    deposits.value AS deposits_all,
    tbill.tbill_ratio_percent,
    ((walcl.value - COALESCE(tga.value, (0)::numeric)) - COALESCE(rrp.value, (0)::numeric)) AS fed_net_liquidity
   FROM ((((((( SELECT DISTINCT macro_indicator_values.observation_date
           FROM public.macro_indicator_values) dates
     LEFT JOIN LATERAL ( SELECT v.value
           FROM (public.macro_indicator_values v
             JOIN public.macro_indicator_definition d ON ((v.indicator_id = d.id)))
          WHERE (((d.series_id)::text = 'WALCL'::text) AND (v.observation_date <= dates.observation_date))
          ORDER BY v.observation_date DESC
         LIMIT 1) walcl ON (true))
     LEFT JOIN LATERAL ( SELECT v.value
           FROM (public.macro_indicator_values v
             JOIN public.macro_indicator_definition d ON ((v.indicator_id = d.id)))
          WHERE (((d.series_id)::text = 'WTREGEN'::text) AND (v.observation_date <= dates.observation_date))
          ORDER BY v.observation_date DESC
         LIMIT 1) tga ON (true))
     LEFT JOIN LATERAL ( SELECT v.value
           FROM (public.macro_indicator_values v
             JOIN public.macro_indicator_definition d ON ((v.indicator_id = d.id)))
          WHERE (((d.series_id)::text = 'RRPONTSYD'::text) AND (v.observation_date <= dates.observation_date))
          ORDER BY v.observation_date DESC
         LIMIT 1) rrp ON (true))
     LEFT JOIN LATERAL ( SELECT v.value
           FROM (public.macro_indicator_values v
             JOIN public.macro_indicator_definition d ON ((v.indicator_id = d.id)))
          WHERE (((d.series_id)::text = 'SOFR'::text) AND (v.observation_date <= dates.observation_date))
          ORDER BY v.observation_date DESC
         LIMIT 1) sofr ON (true))
     LEFT JOIN LATERAL ( SELECT v.value
           FROM (public.macro_indicator_values v
             JOIN public.macro_indicator_definition d ON ((v.indicator_id = d.id)))
          WHERE (((d.series_id)::text = 'DPSACBW027SBOG'::text) AND (v.observation_date <= dates.observation_date))
          ORDER BY v.observation_date DESC
         LIMIT 1) deposits ON (true))
     LEFT JOIN LATERAL ( SELECT t.tbill_ratio_percent
           FROM public.vw_treasury_liquidity_mix t
          WHERE (t.observation_date <= dates.observation_date)
          ORDER BY t.observation_date DESC
         LIMIT 1) tbill ON (true))
  ORDER BY dates.observation_date DESC;


create or replace view "public"."vw_global_liquidity_score" as  WITH global_dates AS (
         SELECT macro_indicator_values.observation_date
           FROM public.macro_indicator_values
        UNION
         SELECT global_macro_indicator_values.observation_date
           FROM public.global_macro_indicator_values
        ), daily_data AS (
         SELECT d.observation_date,
            us.fed_net_liquidity,
            ( SELECT v.raw_value
                   FROM (public.global_macro_indicator_values v
                     JOIN public.global_macro_indicator_definition def ON ((v.indicator_id = def.id)))
                  WHERE (((def.series_id)::text = 'ECBASSETSW'::text) AND (v.observation_date <= d.observation_date))
                  ORDER BY v.observation_date DESC
                 LIMIT 1) AS ecb_assets_eur,
            ( SELECT v.raw_value
                   FROM (public.global_macro_indicator_values v
                     JOIN public.global_macro_indicator_definition def ON ((v.indicator_id = def.id)))
                  WHERE (((def.series_id)::text = 'JPNASSETS'::text) AND (v.observation_date <= d.observation_date))
                  ORDER BY v.observation_date DESC
                 LIMIT 1) AS boj_assets_jpy_100m,
            ( SELECT v.raw_value
                   FROM (public.global_macro_indicator_values v
                     JOIN public.global_macro_indicator_definition def ON ((v.indicator_id = def.id)))
                  WHERE (((def.series_id)::text = 'WLRRAFOIAL'::text) AND (v.observation_date <= d.observation_date))
                  ORDER BY v.observation_date DESC
                 LIMIT 1) AS foreign_repo_usd,
            ( SELECT fx.rate
                   FROM public.fx_rates_daily fx
                  WHERE (((fx.currency_pair)::text = 'EURUSD'::text) AND (fx.observation_date <= d.observation_date))
                  ORDER BY fx.observation_date DESC
                 LIMIT 1) AS eurusd_rate,
            ( SELECT fx.rate
                   FROM public.fx_rates_daily fx
                  WHERE (((fx.currency_pair)::text = 'USDJPY'::text) AND (fx.observation_date <= d.observation_date))
                  ORDER BY fx.observation_date DESC
                 LIMIT 1) AS usdjpy_rate
           FROM (global_dates d
             LEFT JOIN public.vw_us_liquidity_score us ON ((d.observation_date = us.observation_date)))
        )
 SELECT observation_date,
    fed_net_liquidity,
    (ecb_assets_eur * eurusd_rate) AS ecb_assets_usd,
    ((boj_assets_jpy_100m * (100)::numeric) / NULLIF(usdjpy_rate, (0)::numeric)) AS boj_assets_usd,
    foreign_repo_usd,
    (((COALESCE(fed_net_liquidity, (0)::numeric) + COALESCE((ecb_assets_eur * eurusd_rate), (0)::numeric)) + COALESCE(((boj_assets_jpy_100m * (100)::numeric) / NULLIF(usdjpy_rate, (0)::numeric)), (0)::numeric)) - COALESCE(foreign_repo_usd, (0)::numeric)) AS global_net_liquidity_usd
   FROM daily_data
  ORDER BY observation_date DESC;


create or replace view "public"."vw_liquidity_ampel" as  WITH daily_options AS (
         SELECT date(option_chain_snapshots.scraped_at) AS obs_date,
            sum(
                CASE
                    WHEN ((option_chain_snapshots.option_type)::text = 'PUT'::text) THEN option_chain_snapshots.volume
                    ELSE (0)::bigint
                END) AS put_volume,
            sum(
                CASE
                    WHEN ((option_chain_snapshots.option_type)::text = 'CALL'::text) THEN option_chain_snapshots.volume
                    ELSE (0)::bigint
                END) AS call_volume,
                CASE
                    WHEN (sum(
                    CASE
                        WHEN ((option_chain_snapshots.option_type)::text = 'CALL'::text) THEN option_chain_snapshots.volume
                        ELSE (0)::bigint
                    END) > (0)::numeric) THEN round((sum(
                    CASE
                        WHEN ((option_chain_snapshots.option_type)::text = 'PUT'::text) THEN option_chain_snapshots.volume
                        ELSE (0)::bigint
                    END) / sum(
                    CASE
                        WHEN ((option_chain_snapshots.option_type)::text = 'CALL'::text) THEN option_chain_snapshots.volume
                        ELSE (0)::bigint
                    END)), 2)
                    ELSE 1.00
                END AS put_call_ratio
           FROM public.option_chain_snapshots
          GROUP BY (date(option_chain_snapshots.scraped_at))
        ), liquidity_momentum AS (
         SELECT vw_us_liquidity_score.observation_date,
            vw_us_liquidity_score.fed_net_liquidity,
            vw_us_liquidity_score.tga_balance,
            lag(vw_us_liquidity_score.fed_net_liquidity, 5) OVER (ORDER BY vw_us_liquidity_score.observation_date) AS liq_5d_ago
           FROM public.vw_us_liquidity_score
        )
 SELECT l.observation_date,
    l.fed_net_liquidity,
    (l.fed_net_liquidity - l.liq_5d_ago) AS liq_momentum_5d,
    COALESCE(o.put_call_ratio, 1.00) AS put_call_ratio,
        CASE
            WHEN (((l.fed_net_liquidity - l.liq_5d_ago) < ('-50000'::integer)::numeric) AND (COALESCE(o.put_call_ratio, 1.00) > 1.10)) THEN 'ROT (Raus hier / Hedgen)'::text
            WHEN (((l.fed_net_liquidity - l.liq_5d_ago) < (0)::numeric) OR (COALESCE(o.put_call_ratio, 1.00) > 1.00)) THEN 'GELB (Vorsicht / Stop Loss anpassen)'::text
            ELSE 'GRÜN (Risk On)'::text
        END AS ampel_status
   FROM (liquidity_momentum l
     LEFT JOIN daily_options o ON ((l.observation_date = o.obs_date)))
  ORDER BY l.observation_date DESC;


create or replace view "public"."vw_global_liquidity_ampel" as  WITH global_momentum AS (
         SELECT vw_global_liquidity_score.observation_date,
            vw_global_liquidity_score.global_net_liquidity_usd,
            lag(vw_global_liquidity_score.global_net_liquidity_usd, 14) OVER (ORDER BY vw_global_liquidity_score.observation_date) AS liq_14d_ago
           FROM public.vw_global_liquidity_score
        ), daily_options AS (
         SELECT date(option_chain_snapshots.scraped_at) AS obs_date,
                CASE
                    WHEN (sum(
                    CASE
                        WHEN ((option_chain_snapshots.option_type)::text = 'CALL'::text) THEN option_chain_snapshots.volume
                        ELSE (0)::bigint
                    END) > (0)::numeric) THEN round((sum(
                    CASE
                        WHEN ((option_chain_snapshots.option_type)::text = 'PUT'::text) THEN option_chain_snapshots.volume
                        ELSE (0)::bigint
                    END) / sum(
                    CASE
                        WHEN ((option_chain_snapshots.option_type)::text = 'CALL'::text) THEN option_chain_snapshots.volume
                        ELSE (0)::bigint
                    END)), 2)
                    ELSE 1.00
                END AS put_call_ratio
           FROM public.option_chain_snapshots
          GROUP BY (date(option_chain_snapshots.scraped_at))
        )
 SELECT g.observation_date,
    g.global_net_liquidity_usd,
    (g.global_net_liquidity_usd - g.liq_14d_ago) AS liq_momentum_14d,
    COALESCE(o.put_call_ratio, 1.00) AS put_call_ratio,
        CASE
            WHEN (((g.global_net_liquidity_usd - g.liq_14d_ago) <= ('-100000'::integer)::numeric) AND (COALESCE(o.put_call_ratio, 1.00) >= 1.10)) THEN 'ROT (Struktureller Drain / Hedgen)'::text
            WHEN (((g.global_net_liquidity_usd - g.liq_14d_ago) < (0)::numeric) OR (COALESCE(o.put_call_ratio, 1.00) >= 1.00)) THEN 'GELB (Vorsicht / Warnstufe)'::text
            ELSE 'GRÜN (Risk On / Expansion)'::text
        END AS global_ampel_status
   FROM (global_momentum g
     LEFT JOIN daily_options o ON ((g.observation_date = o.obs_date)))
  ORDER BY g.observation_date DESC;


grant delete on table "public"."cboe_options_volume" to "anon";

grant insert on table "public"."cboe_options_volume" to "anon";

grant references on table "public"."cboe_options_volume" to "anon";

grant select on table "public"."cboe_options_volume" to "anon";

grant trigger on table "public"."cboe_options_volume" to "anon";

grant truncate on table "public"."cboe_options_volume" to "anon";

grant update on table "public"."cboe_options_volume" to "anon";

grant delete on table "public"."cboe_options_volume" to "authenticated";

grant insert on table "public"."cboe_options_volume" to "authenticated";

grant references on table "public"."cboe_options_volume" to "authenticated";

grant select on table "public"."cboe_options_volume" to "authenticated";

grant trigger on table "public"."cboe_options_volume" to "authenticated";

grant truncate on table "public"."cboe_options_volume" to "authenticated";

grant update on table "public"."cboe_options_volume" to "authenticated";

grant delete on table "public"."cboe_options_volume" to "service_role";

grant insert on table "public"."cboe_options_volume" to "service_role";

grant references on table "public"."cboe_options_volume" to "service_role";

grant select on table "public"."cboe_options_volume" to "service_role";

grant trigger on table "public"."cboe_options_volume" to "service_role";

grant truncate on table "public"."cboe_options_volume" to "service_role";

grant update on table "public"."cboe_options_volume" to "service_role";

grant delete on table "public"."daily_candles" to "anon";

grant insert on table "public"."daily_candles" to "anon";

grant references on table "public"."daily_candles" to "anon";

grant select on table "public"."daily_candles" to "anon";

grant trigger on table "public"."daily_candles" to "anon";

grant truncate on table "public"."daily_candles" to "anon";

grant update on table "public"."daily_candles" to "anon";

grant delete on table "public"."daily_candles" to "authenticated";

grant insert on table "public"."daily_candles" to "authenticated";

grant references on table "public"."daily_candles" to "authenticated";

grant select on table "public"."daily_candles" to "authenticated";

grant trigger on table "public"."daily_candles" to "authenticated";

grant truncate on table "public"."daily_candles" to "authenticated";

grant update on table "public"."daily_candles" to "authenticated";

grant delete on table "public"."daily_candles" to "service_role";

grant insert on table "public"."daily_candles" to "service_role";

grant references on table "public"."daily_candles" to "service_role";

grant select on table "public"."daily_candles" to "service_role";

grant trigger on table "public"."daily_candles" to "service_role";

grant truncate on table "public"."daily_candles" to "service_role";

grant update on table "public"."daily_candles" to "service_role";

grant delete on table "public"."eodhd_sync_queue" to "anon";

grant insert on table "public"."eodhd_sync_queue" to "anon";

grant references on table "public"."eodhd_sync_queue" to "anon";

grant select on table "public"."eodhd_sync_queue" to "anon";

grant trigger on table "public"."eodhd_sync_queue" to "anon";

grant truncate on table "public"."eodhd_sync_queue" to "anon";

grant update on table "public"."eodhd_sync_queue" to "anon";

grant delete on table "public"."eodhd_sync_queue" to "authenticated";

grant insert on table "public"."eodhd_sync_queue" to "authenticated";

grant references on table "public"."eodhd_sync_queue" to "authenticated";

grant select on table "public"."eodhd_sync_queue" to "authenticated";

grant trigger on table "public"."eodhd_sync_queue" to "authenticated";

grant truncate on table "public"."eodhd_sync_queue" to "authenticated";

grant update on table "public"."eodhd_sync_queue" to "authenticated";

grant delete on table "public"."eodhd_sync_queue" to "service_role";

grant insert on table "public"."eodhd_sync_queue" to "service_role";

grant references on table "public"."eodhd_sync_queue" to "service_role";

grant select on table "public"."eodhd_sync_queue" to "service_role";

grant trigger on table "public"."eodhd_sync_queue" to "service_role";

grant truncate on table "public"."eodhd_sync_queue" to "service_role";

grant update on table "public"."eodhd_sync_queue" to "service_role";

grant delete on table "public"."event_calendar" to "anon";

grant insert on table "public"."event_calendar" to "anon";

grant references on table "public"."event_calendar" to "anon";

grant select on table "public"."event_calendar" to "anon";

grant trigger on table "public"."event_calendar" to "anon";

grant truncate on table "public"."event_calendar" to "anon";

grant update on table "public"."event_calendar" to "anon";

grant delete on table "public"."event_calendar" to "authenticated";

grant insert on table "public"."event_calendar" to "authenticated";

grant references on table "public"."event_calendar" to "authenticated";

grant select on table "public"."event_calendar" to "authenticated";

grant trigger on table "public"."event_calendar" to "authenticated";

grant truncate on table "public"."event_calendar" to "authenticated";

grant update on table "public"."event_calendar" to "authenticated";

grant delete on table "public"."event_calendar" to "service_role";

grant insert on table "public"."event_calendar" to "service_role";

grant references on table "public"."event_calendar" to "service_role";

grant select on table "public"."event_calendar" to "service_role";

grant trigger on table "public"."event_calendar" to "service_role";

grant truncate on table "public"."event_calendar" to "service_role";

grant update on table "public"."event_calendar" to "service_role";

grant delete on table "public"."finra_short_volume" to "anon";

grant insert on table "public"."finra_short_volume" to "anon";

grant references on table "public"."finra_short_volume" to "anon";

grant select on table "public"."finra_short_volume" to "anon";

grant trigger on table "public"."finra_short_volume" to "anon";

grant truncate on table "public"."finra_short_volume" to "anon";

grant update on table "public"."finra_short_volume" to "anon";

grant delete on table "public"."finra_short_volume" to "authenticated";

grant insert on table "public"."finra_short_volume" to "authenticated";

grant references on table "public"."finra_short_volume" to "authenticated";

grant select on table "public"."finra_short_volume" to "authenticated";

grant trigger on table "public"."finra_short_volume" to "authenticated";

grant truncate on table "public"."finra_short_volume" to "authenticated";

grant update on table "public"."finra_short_volume" to "authenticated";

grant delete on table "public"."finra_short_volume" to "service_role";

grant insert on table "public"."finra_short_volume" to "service_role";

grant references on table "public"."finra_short_volume" to "service_role";

grant select on table "public"."finra_short_volume" to "service_role";

grant trigger on table "public"."finra_short_volume" to "service_role";

grant truncate on table "public"."finra_short_volume" to "service_role";

grant update on table "public"."finra_short_volume" to "service_role";

grant delete on table "public"."fx_rates_daily" to "anon";

grant insert on table "public"."fx_rates_daily" to "anon";

grant references on table "public"."fx_rates_daily" to "anon";

grant select on table "public"."fx_rates_daily" to "anon";

grant trigger on table "public"."fx_rates_daily" to "anon";

grant truncate on table "public"."fx_rates_daily" to "anon";

grant update on table "public"."fx_rates_daily" to "anon";

grant delete on table "public"."fx_rates_daily" to "authenticated";

grant insert on table "public"."fx_rates_daily" to "authenticated";

grant references on table "public"."fx_rates_daily" to "authenticated";

grant select on table "public"."fx_rates_daily" to "authenticated";

grant trigger on table "public"."fx_rates_daily" to "authenticated";

grant truncate on table "public"."fx_rates_daily" to "authenticated";

grant update on table "public"."fx_rates_daily" to "authenticated";

grant delete on table "public"."fx_rates_daily" to "service_role";

grant insert on table "public"."fx_rates_daily" to "service_role";

grant references on table "public"."fx_rates_daily" to "service_role";

grant select on table "public"."fx_rates_daily" to "service_role";

grant trigger on table "public"."fx_rates_daily" to "service_role";

grant truncate on table "public"."fx_rates_daily" to "service_role";

grant update on table "public"."fx_rates_daily" to "service_role";

grant delete on table "public"."global_macro_indicator_definition" to "anon";

grant insert on table "public"."global_macro_indicator_definition" to "anon";

grant references on table "public"."global_macro_indicator_definition" to "anon";

grant select on table "public"."global_macro_indicator_definition" to "anon";

grant trigger on table "public"."global_macro_indicator_definition" to "anon";

grant truncate on table "public"."global_macro_indicator_definition" to "anon";

grant update on table "public"."global_macro_indicator_definition" to "anon";

grant delete on table "public"."global_macro_indicator_definition" to "authenticated";

grant insert on table "public"."global_macro_indicator_definition" to "authenticated";

grant references on table "public"."global_macro_indicator_definition" to "authenticated";

grant select on table "public"."global_macro_indicator_definition" to "authenticated";

grant trigger on table "public"."global_macro_indicator_definition" to "authenticated";

grant truncate on table "public"."global_macro_indicator_definition" to "authenticated";

grant update on table "public"."global_macro_indicator_definition" to "authenticated";

grant delete on table "public"."global_macro_indicator_definition" to "service_role";

grant insert on table "public"."global_macro_indicator_definition" to "service_role";

grant references on table "public"."global_macro_indicator_definition" to "service_role";

grant select on table "public"."global_macro_indicator_definition" to "service_role";

grant trigger on table "public"."global_macro_indicator_definition" to "service_role";

grant truncate on table "public"."global_macro_indicator_definition" to "service_role";

grant update on table "public"."global_macro_indicator_definition" to "service_role";

grant delete on table "public"."global_macro_indicator_values" to "anon";

grant insert on table "public"."global_macro_indicator_values" to "anon";

grant references on table "public"."global_macro_indicator_values" to "anon";

grant select on table "public"."global_macro_indicator_values" to "anon";

grant trigger on table "public"."global_macro_indicator_values" to "anon";

grant truncate on table "public"."global_macro_indicator_values" to "anon";

grant update on table "public"."global_macro_indicator_values" to "anon";

grant delete on table "public"."global_macro_indicator_values" to "authenticated";

grant insert on table "public"."global_macro_indicator_values" to "authenticated";

grant references on table "public"."global_macro_indicator_values" to "authenticated";

grant select on table "public"."global_macro_indicator_values" to "authenticated";

grant trigger on table "public"."global_macro_indicator_values" to "authenticated";

grant truncate on table "public"."global_macro_indicator_values" to "authenticated";

grant update on table "public"."global_macro_indicator_values" to "authenticated";

grant delete on table "public"."global_macro_indicator_values" to "service_role";

grant insert on table "public"."global_macro_indicator_values" to "service_role";

grant references on table "public"."global_macro_indicator_values" to "service_role";

grant select on table "public"."global_macro_indicator_values" to "service_role";

grant trigger on table "public"."global_macro_indicator_values" to "service_role";

grant truncate on table "public"."global_macro_indicator_values" to "service_role";

grant update on table "public"."global_macro_indicator_values" to "service_role";

grant delete on table "public"."labor_market_data_points" to "anon";

grant insert on table "public"."labor_market_data_points" to "anon";

grant references on table "public"."labor_market_data_points" to "anon";

grant select on table "public"."labor_market_data_points" to "anon";

grant trigger on table "public"."labor_market_data_points" to "anon";

grant truncate on table "public"."labor_market_data_points" to "anon";

grant update on table "public"."labor_market_data_points" to "anon";

grant delete on table "public"."labor_market_data_points" to "authenticated";

grant insert on table "public"."labor_market_data_points" to "authenticated";

grant references on table "public"."labor_market_data_points" to "authenticated";

grant select on table "public"."labor_market_data_points" to "authenticated";

grant trigger on table "public"."labor_market_data_points" to "authenticated";

grant truncate on table "public"."labor_market_data_points" to "authenticated";

grant update on table "public"."labor_market_data_points" to "authenticated";

grant delete on table "public"."labor_market_data_points" to "service_role";

grant insert on table "public"."labor_market_data_points" to "service_role";

grant references on table "public"."labor_market_data_points" to "service_role";

grant select on table "public"."labor_market_data_points" to "service_role";

grant trigger on table "public"."labor_market_data_points" to "service_role";

grant truncate on table "public"."labor_market_data_points" to "service_role";

grant update on table "public"."labor_market_data_points" to "service_role";

grant delete on table "public"."labor_market_series" to "anon";

grant insert on table "public"."labor_market_series" to "anon";

grant references on table "public"."labor_market_series" to "anon";

grant select on table "public"."labor_market_series" to "anon";

grant trigger on table "public"."labor_market_series" to "anon";

grant truncate on table "public"."labor_market_series" to "anon";

grant update on table "public"."labor_market_series" to "anon";

grant delete on table "public"."labor_market_series" to "authenticated";

grant insert on table "public"."labor_market_series" to "authenticated";

grant references on table "public"."labor_market_series" to "authenticated";

grant select on table "public"."labor_market_series" to "authenticated";

grant trigger on table "public"."labor_market_series" to "authenticated";

grant truncate on table "public"."labor_market_series" to "authenticated";

grant update on table "public"."labor_market_series" to "authenticated";

grant delete on table "public"."labor_market_series" to "service_role";

grant insert on table "public"."labor_market_series" to "service_role";

grant references on table "public"."labor_market_series" to "service_role";

grant select on table "public"."labor_market_series" to "service_role";

grant trigger on table "public"."labor_market_series" to "service_role";

grant truncate on table "public"."labor_market_series" to "service_role";

grant update on table "public"."labor_market_series" to "service_role";

grant delete on table "public"."m5_candles" to "anon";

grant insert on table "public"."m5_candles" to "anon";

grant references on table "public"."m5_candles" to "anon";

grant select on table "public"."m5_candles" to "anon";

grant trigger on table "public"."m5_candles" to "anon";

grant truncate on table "public"."m5_candles" to "anon";

grant update on table "public"."m5_candles" to "anon";

grant delete on table "public"."m5_candles" to "authenticated";

grant insert on table "public"."m5_candles" to "authenticated";

grant references on table "public"."m5_candles" to "authenticated";

grant select on table "public"."m5_candles" to "authenticated";

grant trigger on table "public"."m5_candles" to "authenticated";

grant truncate on table "public"."m5_candles" to "authenticated";

grant update on table "public"."m5_candles" to "authenticated";

grant delete on table "public"."m5_candles" to "service_role";

grant insert on table "public"."m5_candles" to "service_role";

grant references on table "public"."m5_candles" to "service_role";

grant select on table "public"."m5_candles" to "service_role";

grant trigger on table "public"."m5_candles" to "service_role";

grant truncate on table "public"."m5_candles" to "service_role";

grant update on table "public"."m5_candles" to "service_role";

grant delete on table "public"."macro_indicator_definition" to "anon";

grant insert on table "public"."macro_indicator_definition" to "anon";

grant references on table "public"."macro_indicator_definition" to "anon";

grant select on table "public"."macro_indicator_definition" to "anon";

grant trigger on table "public"."macro_indicator_definition" to "anon";

grant truncate on table "public"."macro_indicator_definition" to "anon";

grant update on table "public"."macro_indicator_definition" to "anon";

grant delete on table "public"."macro_indicator_definition" to "authenticated";

grant insert on table "public"."macro_indicator_definition" to "authenticated";

grant references on table "public"."macro_indicator_definition" to "authenticated";

grant select on table "public"."macro_indicator_definition" to "authenticated";

grant trigger on table "public"."macro_indicator_definition" to "authenticated";

grant truncate on table "public"."macro_indicator_definition" to "authenticated";

grant update on table "public"."macro_indicator_definition" to "authenticated";

grant delete on table "public"."macro_indicator_definition" to "service_role";

grant insert on table "public"."macro_indicator_definition" to "service_role";

grant references on table "public"."macro_indicator_definition" to "service_role";

grant select on table "public"."macro_indicator_definition" to "service_role";

grant trigger on table "public"."macro_indicator_definition" to "service_role";

grant truncate on table "public"."macro_indicator_definition" to "service_role";

grant update on table "public"."macro_indicator_definition" to "service_role";

grant delete on table "public"."macro_indicator_values" to "anon";

grant insert on table "public"."macro_indicator_values" to "anon";

grant references on table "public"."macro_indicator_values" to "anon";

grant select on table "public"."macro_indicator_values" to "anon";

grant trigger on table "public"."macro_indicator_values" to "anon";

grant truncate on table "public"."macro_indicator_values" to "anon";

grant update on table "public"."macro_indicator_values" to "anon";

grant delete on table "public"."macro_indicator_values" to "authenticated";

grant insert on table "public"."macro_indicator_values" to "authenticated";

grant references on table "public"."macro_indicator_values" to "authenticated";

grant select on table "public"."macro_indicator_values" to "authenticated";

grant trigger on table "public"."macro_indicator_values" to "authenticated";

grant truncate on table "public"."macro_indicator_values" to "authenticated";

grant update on table "public"."macro_indicator_values" to "authenticated";

grant delete on table "public"."macro_indicator_values" to "service_role";

grant insert on table "public"."macro_indicator_values" to "service_role";

grant references on table "public"."macro_indicator_values" to "service_role";

grant select on table "public"."macro_indicator_values" to "service_role";

grant trigger on table "public"."macro_indicator_values" to "service_role";

grant truncate on table "public"."macro_indicator_values" to "service_role";

grant update on table "public"."macro_indicator_values" to "service_role";

grant delete on table "public"."macro_liquidity" to "anon";

grant insert on table "public"."macro_liquidity" to "anon";

grant references on table "public"."macro_liquidity" to "anon";

grant select on table "public"."macro_liquidity" to "anon";

grant trigger on table "public"."macro_liquidity" to "anon";

grant truncate on table "public"."macro_liquidity" to "anon";

grant update on table "public"."macro_liquidity" to "anon";

grant delete on table "public"."macro_liquidity" to "authenticated";

grant insert on table "public"."macro_liquidity" to "authenticated";

grant references on table "public"."macro_liquidity" to "authenticated";

grant select on table "public"."macro_liquidity" to "authenticated";

grant trigger on table "public"."macro_liquidity" to "authenticated";

grant truncate on table "public"."macro_liquidity" to "authenticated";

grant update on table "public"."macro_liquidity" to "authenticated";

grant delete on table "public"."macro_liquidity" to "service_role";

grant insert on table "public"."macro_liquidity" to "service_role";

grant references on table "public"."macro_liquidity" to "service_role";

grant select on table "public"."macro_liquidity" to "service_role";

grant trigger on table "public"."macro_liquidity" to "service_role";

grant truncate on table "public"."macro_liquidity" to "service_role";

grant update on table "public"."macro_liquidity" to "service_role";

grant delete on table "public"."macro_news_feed" to "anon";

grant insert on table "public"."macro_news_feed" to "anon";

grant references on table "public"."macro_news_feed" to "anon";

grant select on table "public"."macro_news_feed" to "anon";

grant trigger on table "public"."macro_news_feed" to "anon";

grant truncate on table "public"."macro_news_feed" to "anon";

grant update on table "public"."macro_news_feed" to "anon";

grant delete on table "public"."macro_news_feed" to "authenticated";

grant insert on table "public"."macro_news_feed" to "authenticated";

grant references on table "public"."macro_news_feed" to "authenticated";

grant select on table "public"."macro_news_feed" to "authenticated";

grant trigger on table "public"."macro_news_feed" to "authenticated";

grant truncate on table "public"."macro_news_feed" to "authenticated";

grant update on table "public"."macro_news_feed" to "authenticated";

grant delete on table "public"."macro_news_feed" to "service_role";

grant insert on table "public"."macro_news_feed" to "service_role";

grant references on table "public"."macro_news_feed" to "service_role";

grant select on table "public"."macro_news_feed" to "service_role";

grant trigger on table "public"."macro_news_feed" to "service_role";

grant truncate on table "public"."macro_news_feed" to "service_role";

grant update on table "public"."macro_news_feed" to "service_role";

grant delete on table "public"."market_sentiment_daily" to "anon";

grant insert on table "public"."market_sentiment_daily" to "anon";

grant references on table "public"."market_sentiment_daily" to "anon";

grant select on table "public"."market_sentiment_daily" to "anon";

grant trigger on table "public"."market_sentiment_daily" to "anon";

grant truncate on table "public"."market_sentiment_daily" to "anon";

grant update on table "public"."market_sentiment_daily" to "anon";

grant delete on table "public"."market_sentiment_daily" to "authenticated";

grant insert on table "public"."market_sentiment_daily" to "authenticated";

grant references on table "public"."market_sentiment_daily" to "authenticated";

grant select on table "public"."market_sentiment_daily" to "authenticated";

grant trigger on table "public"."market_sentiment_daily" to "authenticated";

grant truncate on table "public"."market_sentiment_daily" to "authenticated";

grant update on table "public"."market_sentiment_daily" to "authenticated";

grant delete on table "public"."market_sentiment_daily" to "service_role";

grant insert on table "public"."market_sentiment_daily" to "service_role";

grant references on table "public"."market_sentiment_daily" to "service_role";

grant select on table "public"."market_sentiment_daily" to "service_role";

grant trigger on table "public"."market_sentiment_daily" to "service_role";

grant truncate on table "public"."market_sentiment_daily" to "service_role";

grant update on table "public"."market_sentiment_daily" to "service_role";

grant delete on table "public"."option_chain_snapshots" to "anon";

grant insert on table "public"."option_chain_snapshots" to "anon";

grant references on table "public"."option_chain_snapshots" to "anon";

grant select on table "public"."option_chain_snapshots" to "anon";

grant trigger on table "public"."option_chain_snapshots" to "anon";

grant truncate on table "public"."option_chain_snapshots" to "anon";

grant update on table "public"."option_chain_snapshots" to "anon";

grant delete on table "public"."option_chain_snapshots" to "authenticated";

grant insert on table "public"."option_chain_snapshots" to "authenticated";

grant references on table "public"."option_chain_snapshots" to "authenticated";

grant select on table "public"."option_chain_snapshots" to "authenticated";

grant trigger on table "public"."option_chain_snapshots" to "authenticated";

grant truncate on table "public"."option_chain_snapshots" to "authenticated";

grant update on table "public"."option_chain_snapshots" to "authenticated";

grant delete on table "public"."option_chain_snapshots" to "service_role";

grant insert on table "public"."option_chain_snapshots" to "service_role";

grant references on table "public"."option_chain_snapshots" to "service_role";

grant select on table "public"."option_chain_snapshots" to "service_role";

grant trigger on table "public"."option_chain_snapshots" to "service_role";

grant truncate on table "public"."option_chain_snapshots" to "service_role";

grant update on table "public"."option_chain_snapshots" to "service_role";

grant delete on table "public"."option_contract_bars" to "anon";

grant insert on table "public"."option_contract_bars" to "anon";

grant references on table "public"."option_contract_bars" to "anon";

grant select on table "public"."option_contract_bars" to "anon";

grant trigger on table "public"."option_contract_bars" to "anon";

grant truncate on table "public"."option_contract_bars" to "anon";

grant update on table "public"."option_contract_bars" to "anon";

grant delete on table "public"."option_contract_bars" to "authenticated";

grant insert on table "public"."option_contract_bars" to "authenticated";

grant references on table "public"."option_contract_bars" to "authenticated";

grant select on table "public"."option_contract_bars" to "authenticated";

grant trigger on table "public"."option_contract_bars" to "authenticated";

grant truncate on table "public"."option_contract_bars" to "authenticated";

grant update on table "public"."option_contract_bars" to "authenticated";

grant delete on table "public"."option_contract_bars" to "service_role";

grant insert on table "public"."option_contract_bars" to "service_role";

grant references on table "public"."option_contract_bars" to "service_role";

grant select on table "public"."option_contract_bars" to "service_role";

grant trigger on table "public"."option_contract_bars" to "service_role";

grant truncate on table "public"."option_contract_bars" to "service_role";

grant update on table "public"."option_contract_bars" to "service_role";

grant delete on table "public"."regulation_alerts" to "anon";

grant insert on table "public"."regulation_alerts" to "anon";

grant references on table "public"."regulation_alerts" to "anon";

grant select on table "public"."regulation_alerts" to "anon";

grant trigger on table "public"."regulation_alerts" to "anon";

grant truncate on table "public"."regulation_alerts" to "anon";

grant update on table "public"."regulation_alerts" to "anon";

grant delete on table "public"."regulation_alerts" to "authenticated";

grant insert on table "public"."regulation_alerts" to "authenticated";

grant references on table "public"."regulation_alerts" to "authenticated";

grant select on table "public"."regulation_alerts" to "authenticated";

grant trigger on table "public"."regulation_alerts" to "authenticated";

grant truncate on table "public"."regulation_alerts" to "authenticated";

grant update on table "public"."regulation_alerts" to "authenticated";

grant delete on table "public"."regulation_alerts" to "service_role";

grant insert on table "public"."regulation_alerts" to "service_role";

grant references on table "public"."regulation_alerts" to "service_role";

grant select on table "public"."regulation_alerts" to "service_role";

grant trigger on table "public"."regulation_alerts" to "service_role";

grant truncate on table "public"."regulation_alerts" to "service_role";

grant update on table "public"."regulation_alerts" to "service_role";

grant delete on table "public"."reserve_requirements" to "anon";

grant insert on table "public"."reserve_requirements" to "anon";

grant references on table "public"."reserve_requirements" to "anon";

grant select on table "public"."reserve_requirements" to "anon";

grant trigger on table "public"."reserve_requirements" to "anon";

grant truncate on table "public"."reserve_requirements" to "anon";

grant update on table "public"."reserve_requirements" to "anon";

grant delete on table "public"."reserve_requirements" to "authenticated";

grant insert on table "public"."reserve_requirements" to "authenticated";

grant references on table "public"."reserve_requirements" to "authenticated";

grant select on table "public"."reserve_requirements" to "authenticated";

grant trigger on table "public"."reserve_requirements" to "authenticated";

grant truncate on table "public"."reserve_requirements" to "authenticated";

grant update on table "public"."reserve_requirements" to "authenticated";

grant delete on table "public"."reserve_requirements" to "service_role";

grant insert on table "public"."reserve_requirements" to "service_role";

grant references on table "public"."reserve_requirements" to "service_role";

grant select on table "public"."reserve_requirements" to "service_role";

grant trigger on table "public"."reserve_requirements" to "service_role";

grant truncate on table "public"."reserve_requirements" to "service_role";

grant update on table "public"."reserve_requirements" to "service_role";

grant delete on table "public"."sec_ai_signals" to "anon";

grant insert on table "public"."sec_ai_signals" to "anon";

grant references on table "public"."sec_ai_signals" to "anon";

grant select on table "public"."sec_ai_signals" to "anon";

grant trigger on table "public"."sec_ai_signals" to "anon";

grant truncate on table "public"."sec_ai_signals" to "anon";

grant update on table "public"."sec_ai_signals" to "anon";

grant delete on table "public"."sec_ai_signals" to "authenticated";

grant insert on table "public"."sec_ai_signals" to "authenticated";

grant references on table "public"."sec_ai_signals" to "authenticated";

grant select on table "public"."sec_ai_signals" to "authenticated";

grant trigger on table "public"."sec_ai_signals" to "authenticated";

grant truncate on table "public"."sec_ai_signals" to "authenticated";

grant update on table "public"."sec_ai_signals" to "authenticated";

grant delete on table "public"."sec_ai_signals" to "service_role";

grant insert on table "public"."sec_ai_signals" to "service_role";

grant references on table "public"."sec_ai_signals" to "service_role";

grant select on table "public"."sec_ai_signals" to "service_role";

grant trigger on table "public"."sec_ai_signals" to "service_role";

grant truncate on table "public"."sec_ai_signals" to "service_role";

grant update on table "public"."sec_ai_signals" to "service_role";

grant delete on table "public"."sec_companies" to "anon";

grant insert on table "public"."sec_companies" to "anon";

grant references on table "public"."sec_companies" to "anon";

grant select on table "public"."sec_companies" to "anon";

grant trigger on table "public"."sec_companies" to "anon";

grant truncate on table "public"."sec_companies" to "anon";

grant update on table "public"."sec_companies" to "anon";

grant delete on table "public"."sec_companies" to "authenticated";

grant insert on table "public"."sec_companies" to "authenticated";

grant references on table "public"."sec_companies" to "authenticated";

grant select on table "public"."sec_companies" to "authenticated";

grant trigger on table "public"."sec_companies" to "authenticated";

grant truncate on table "public"."sec_companies" to "authenticated";

grant update on table "public"."sec_companies" to "authenticated";

grant delete on table "public"."sec_companies" to "service_role";

grant insert on table "public"."sec_companies" to "service_role";

grant references on table "public"."sec_companies" to "service_role";

grant select on table "public"."sec_companies" to "service_role";

grant trigger on table "public"."sec_companies" to "service_role";

grant truncate on table "public"."sec_companies" to "service_role";

grant update on table "public"."sec_companies" to "service_role";

grant delete on table "public"."sec_companies_keywords" to "anon";

grant insert on table "public"."sec_companies_keywords" to "anon";

grant references on table "public"."sec_companies_keywords" to "anon";

grant select on table "public"."sec_companies_keywords" to "anon";

grant trigger on table "public"."sec_companies_keywords" to "anon";

grant truncate on table "public"."sec_companies_keywords" to "anon";

grant update on table "public"."sec_companies_keywords" to "anon";

grant delete on table "public"."sec_companies_keywords" to "authenticated";

grant insert on table "public"."sec_companies_keywords" to "authenticated";

grant references on table "public"."sec_companies_keywords" to "authenticated";

grant select on table "public"."sec_companies_keywords" to "authenticated";

grant trigger on table "public"."sec_companies_keywords" to "authenticated";

grant truncate on table "public"."sec_companies_keywords" to "authenticated";

grant update on table "public"."sec_companies_keywords" to "authenticated";

grant delete on table "public"."sec_companies_keywords" to "service_role";

grant insert on table "public"."sec_companies_keywords" to "service_role";

grant references on table "public"."sec_companies_keywords" to "service_role";

grant select on table "public"."sec_companies_keywords" to "service_role";

grant trigger on table "public"."sec_companies_keywords" to "service_role";

grant truncate on table "public"."sec_companies_keywords" to "service_role";

grant update on table "public"."sec_companies_keywords" to "service_role";

grant delete on table "public"."sec_fmp_fundamentals" to "anon";

grant insert on table "public"."sec_fmp_fundamentals" to "anon";

grant references on table "public"."sec_fmp_fundamentals" to "anon";

grant select on table "public"."sec_fmp_fundamentals" to "anon";

grant trigger on table "public"."sec_fmp_fundamentals" to "anon";

grant truncate on table "public"."sec_fmp_fundamentals" to "anon";

grant update on table "public"."sec_fmp_fundamentals" to "anon";

grant delete on table "public"."sec_fmp_fundamentals" to "authenticated";

grant insert on table "public"."sec_fmp_fundamentals" to "authenticated";

grant references on table "public"."sec_fmp_fundamentals" to "authenticated";

grant select on table "public"."sec_fmp_fundamentals" to "authenticated";

grant trigger on table "public"."sec_fmp_fundamentals" to "authenticated";

grant truncate on table "public"."sec_fmp_fundamentals" to "authenticated";

grant update on table "public"."sec_fmp_fundamentals" to "authenticated";

grant delete on table "public"."sec_fmp_fundamentals" to "service_role";

grant insert on table "public"."sec_fmp_fundamentals" to "service_role";

grant references on table "public"."sec_fmp_fundamentals" to "service_role";

grant select on table "public"."sec_fmp_fundamentals" to "service_role";

grant trigger on table "public"."sec_fmp_fundamentals" to "service_role";

grant truncate on table "public"."sec_fmp_fundamentals" to "service_role";

grant update on table "public"."sec_fmp_fundamentals" to "service_role";

grant delete on table "public"."sec_raw_filings" to "anon";

grant insert on table "public"."sec_raw_filings" to "anon";

grant references on table "public"."sec_raw_filings" to "anon";

grant select on table "public"."sec_raw_filings" to "anon";

grant trigger on table "public"."sec_raw_filings" to "anon";

grant truncate on table "public"."sec_raw_filings" to "anon";

grant update on table "public"."sec_raw_filings" to "anon";

grant delete on table "public"."sec_raw_filings" to "authenticated";

grant insert on table "public"."sec_raw_filings" to "authenticated";

grant references on table "public"."sec_raw_filings" to "authenticated";

grant select on table "public"."sec_raw_filings" to "authenticated";

grant trigger on table "public"."sec_raw_filings" to "authenticated";

grant truncate on table "public"."sec_raw_filings" to "authenticated";

grant update on table "public"."sec_raw_filings" to "authenticated";

grant delete on table "public"."sec_raw_filings" to "service_role";

grant insert on table "public"."sec_raw_filings" to "service_role";

grant references on table "public"."sec_raw_filings" to "service_role";

grant select on table "public"."sec_raw_filings" to "service_role";

grant trigger on table "public"."sec_raw_filings" to "service_role";

grant truncate on table "public"."sec_raw_filings" to "service_role";

grant update on table "public"."sec_raw_filings" to "service_role";

grant delete on table "public"."sector_rotation_log" to "anon";

grant insert on table "public"."sector_rotation_log" to "anon";

grant references on table "public"."sector_rotation_log" to "anon";

grant select on table "public"."sector_rotation_log" to "anon";

grant trigger on table "public"."sector_rotation_log" to "anon";

grant truncate on table "public"."sector_rotation_log" to "anon";

grant update on table "public"."sector_rotation_log" to "anon";

grant delete on table "public"."sector_rotation_log" to "authenticated";

grant insert on table "public"."sector_rotation_log" to "authenticated";

grant references on table "public"."sector_rotation_log" to "authenticated";

grant select on table "public"."sector_rotation_log" to "authenticated";

grant trigger on table "public"."sector_rotation_log" to "authenticated";

grant truncate on table "public"."sector_rotation_log" to "authenticated";

grant update on table "public"."sector_rotation_log" to "authenticated";

grant delete on table "public"."sector_rotation_log" to "service_role";

grant insert on table "public"."sector_rotation_log" to "service_role";

grant references on table "public"."sector_rotation_log" to "service_role";

grant select on table "public"."sector_rotation_log" to "service_role";

grant trigger on table "public"."sector_rotation_log" to "service_role";

grant truncate on table "public"."sector_rotation_log" to "service_role";

grant update on table "public"."sector_rotation_log" to "service_role";

grant delete on table "public"."ticker" to "anon";

grant insert on table "public"."ticker" to "anon";

grant references on table "public"."ticker" to "anon";

grant select on table "public"."ticker" to "anon";

grant trigger on table "public"."ticker" to "anon";

grant truncate on table "public"."ticker" to "anon";

grant update on table "public"."ticker" to "anon";

grant delete on table "public"."ticker" to "authenticated";

grant insert on table "public"."ticker" to "authenticated";

grant references on table "public"."ticker" to "authenticated";

grant select on table "public"."ticker" to "authenticated";

grant trigger on table "public"."ticker" to "authenticated";

grant truncate on table "public"."ticker" to "authenticated";

grant update on table "public"."ticker" to "authenticated";

grant delete on table "public"."ticker" to "service_role";

grant insert on table "public"."ticker" to "service_role";

grant references on table "public"."ticker" to "service_role";

grant select on table "public"."ticker" to "service_role";

grant trigger on table "public"."ticker" to "service_role";

grant truncate on table "public"."ticker" to "service_role";

grant update on table "public"."ticker" to "service_role";

grant delete on table "public"."ticker_data_config" to "anon";

grant insert on table "public"."ticker_data_config" to "anon";

grant references on table "public"."ticker_data_config" to "anon";

grant select on table "public"."ticker_data_config" to "anon";

grant trigger on table "public"."ticker_data_config" to "anon";

grant truncate on table "public"."ticker_data_config" to "anon";

grant update on table "public"."ticker_data_config" to "anon";

grant delete on table "public"."ticker_data_config" to "authenticated";

grant insert on table "public"."ticker_data_config" to "authenticated";

grant references on table "public"."ticker_data_config" to "authenticated";

grant select on table "public"."ticker_data_config" to "authenticated";

grant trigger on table "public"."ticker_data_config" to "authenticated";

grant truncate on table "public"."ticker_data_config" to "authenticated";

grant update on table "public"."ticker_data_config" to "authenticated";

grant delete on table "public"."ticker_data_config" to "service_role";

grant insert on table "public"."ticker_data_config" to "service_role";

grant references on table "public"."ticker_data_config" to "service_role";

grant select on table "public"."ticker_data_config" to "service_role";

grant trigger on table "public"."ticker_data_config" to "service_role";

grant truncate on table "public"."ticker_data_config" to "service_role";

grant update on table "public"."ticker_data_config" to "service_role";

grant delete on table "public"."ticker_dependencies" to "anon";

grant insert on table "public"."ticker_dependencies" to "anon";

grant references on table "public"."ticker_dependencies" to "anon";

grant select on table "public"."ticker_dependencies" to "anon";

grant trigger on table "public"."ticker_dependencies" to "anon";

grant truncate on table "public"."ticker_dependencies" to "anon";

grant update on table "public"."ticker_dependencies" to "anon";

grant delete on table "public"."ticker_dependencies" to "authenticated";

grant insert on table "public"."ticker_dependencies" to "authenticated";

grant references on table "public"."ticker_dependencies" to "authenticated";

grant select on table "public"."ticker_dependencies" to "authenticated";

grant trigger on table "public"."ticker_dependencies" to "authenticated";

grant truncate on table "public"."ticker_dependencies" to "authenticated";

grant update on table "public"."ticker_dependencies" to "authenticated";

grant delete on table "public"."ticker_dependencies" to "service_role";

grant insert on table "public"."ticker_dependencies" to "service_role";

grant references on table "public"."ticker_dependencies" to "service_role";

grant select on table "public"."ticker_dependencies" to "service_role";

grant trigger on table "public"."ticker_dependencies" to "service_role";

grant truncate on table "public"."ticker_dependencies" to "service_role";

grant update on table "public"."ticker_dependencies" to "service_role";

grant delete on table "public"."ticker_typ" to "anon";

grant insert on table "public"."ticker_typ" to "anon";

grant references on table "public"."ticker_typ" to "anon";

grant select on table "public"."ticker_typ" to "anon";

grant trigger on table "public"."ticker_typ" to "anon";

grant truncate on table "public"."ticker_typ" to "anon";

grant update on table "public"."ticker_typ" to "anon";

grant delete on table "public"."ticker_typ" to "authenticated";

grant insert on table "public"."ticker_typ" to "authenticated";

grant references on table "public"."ticker_typ" to "authenticated";

grant select on table "public"."ticker_typ" to "authenticated";

grant trigger on table "public"."ticker_typ" to "authenticated";

grant truncate on table "public"."ticker_typ" to "authenticated";

grant update on table "public"."ticker_typ" to "authenticated";

grant delete on table "public"."ticker_typ" to "service_role";

grant insert on table "public"."ticker_typ" to "service_role";

grant references on table "public"."ticker_typ" to "service_role";

grant select on table "public"."ticker_typ" to "service_role";

grant trigger on table "public"."ticker_typ" to "service_role";

grant truncate on table "public"."ticker_typ" to "service_role";

grant update on table "public"."ticker_typ" to "service_role";

grant delete on table "public"."treasury_auctions" to "anon";

grant insert on table "public"."treasury_auctions" to "anon";

grant references on table "public"."treasury_auctions" to "anon";

grant select on table "public"."treasury_auctions" to "anon";

grant trigger on table "public"."treasury_auctions" to "anon";

grant truncate on table "public"."treasury_auctions" to "anon";

grant update on table "public"."treasury_auctions" to "anon";

grant delete on table "public"."treasury_auctions" to "authenticated";

grant insert on table "public"."treasury_auctions" to "authenticated";

grant references on table "public"."treasury_auctions" to "authenticated";

grant select on table "public"."treasury_auctions" to "authenticated";

grant trigger on table "public"."treasury_auctions" to "authenticated";

grant truncate on table "public"."treasury_auctions" to "authenticated";

grant update on table "public"."treasury_auctions" to "authenticated";

grant delete on table "public"."treasury_auctions" to "service_role";

grant insert on table "public"."treasury_auctions" to "service_role";

grant references on table "public"."treasury_auctions" to "service_role";

grant select on table "public"."treasury_auctions" to "service_role";

grant trigger on table "public"."treasury_auctions" to "service_role";

grant truncate on table "public"."treasury_auctions" to "service_role";

grant update on table "public"."treasury_auctions" to "service_role";

grant delete on table "public"."treasury_qra_estimates" to "anon";

grant insert on table "public"."treasury_qra_estimates" to "anon";

grant references on table "public"."treasury_qra_estimates" to "anon";

grant select on table "public"."treasury_qra_estimates" to "anon";

grant trigger on table "public"."treasury_qra_estimates" to "anon";

grant truncate on table "public"."treasury_qra_estimates" to "anon";

grant update on table "public"."treasury_qra_estimates" to "anon";

grant delete on table "public"."treasury_qra_estimates" to "authenticated";

grant insert on table "public"."treasury_qra_estimates" to "authenticated";

grant references on table "public"."treasury_qra_estimates" to "authenticated";

grant select on table "public"."treasury_qra_estimates" to "authenticated";

grant trigger on table "public"."treasury_qra_estimates" to "authenticated";

grant truncate on table "public"."treasury_qra_estimates" to "authenticated";

grant update on table "public"."treasury_qra_estimates" to "authenticated";

grant delete on table "public"."treasury_qra_estimates" to "service_role";

grant insert on table "public"."treasury_qra_estimates" to "service_role";

grant references on table "public"."treasury_qra_estimates" to "service_role";

grant select on table "public"."treasury_qra_estimates" to "service_role";

grant trigger on table "public"."treasury_qra_estimates" to "service_role";

grant truncate on table "public"."treasury_qra_estimates" to "service_role";

grant update on table "public"."treasury_qra_estimates" to "service_role";


