


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pg_cron" WITH SCHEMA "pg_catalog";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."ai_trend_signal" AS ENUM (
    'EXPANSION',
    'CONTRACTION',
    'OPTIMIZATION',
    'OVERCAPACITY',
    'FLAT'
);


ALTER TYPE "public"."ai_trend_signal" OWNER TO "postgres";


CREATE TYPE "public"."company_archetype" AS ENUM (
    'HYPERSCALER',
    'FOUNDRY',
    'EQUIPMENT',
    'MEMORY',
    'SOFTWARE'
);


ALTER TYPE "public"."company_archetype" OWNER TO "postgres";


CREATE TYPE "public"."sync_job_type" AS ENUM (
    'DAILY',
    'M5',
    'OPTIONS',
    'SHORT_VOLUME',
    'SENTIMENT',
    'EVENTS',
    'SECTOR_ROTATION'
);


ALTER TYPE "public"."sync_job_type" OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."get_missing_sentiment_dates"("target_ticker" "text", "start_date" "date", "exclude_weekends" boolean) RETURNS TABLE("missing_date" "date")
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  RETURN QUERY
  WITH valid_dates AS (
    -- Anstatt generate_series nutzen wir nun die smarte Kalender-Tabelle
    SELECT date AS gs_date 
    FROM public.market_trading_days 
    WHERE date >= start_date 
      AND date <= CURRENT_DATE
      -- Wenn exclude_weekends TRUE ist, liefern wir NUR echte Handelstage (ohne WE/Feiertage) zurück
      AND (exclude_weekends = false OR is_trading_day = true)
  )
  SELECT v.gs_date
  FROM valid_dates v
  LEFT JOIN public.market_sentiment_daily m
    ON m.observation_date = v.gs_date AND m.ticker = target_ticker
  WHERE m.observation_date IS NULL;
END;
$$;


ALTER FUNCTION "public"."get_missing_sentiment_dates"("target_ticker" "text", "start_date" "date", "exclude_weekends" boolean) OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."sys_log_table_operation"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
BEGIN
    INSERT INTO public.sys_insert_logs (table_name, action_type)
    VALUES (TG_TABLE_NAME, TG_OP);
    RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."sys_log_table_operation"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."market_event_calendar" (
    "id" bigint NOT NULL,
    "ticker_id" bigint NOT NULL,
    "ticker_name" character varying(10) NOT NULL,
    "event_typ" character varying(50) NOT NULL,
    "event_datum" "date" NOT NULL,
    "beschreibung" "text",
    "status" character varying(50) DEFAULT 'SCHEDULED'::character varying,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL
);


ALTER TABLE "public"."market_event_calendar" OWNER TO "postgres";


ALTER TABLE "public"."market_event_calendar" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."event_calendar_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."labor_market_data_points" (
    "id" bigint NOT NULL,
    "series_id" character varying(50),
    "data_period" "date" NOT NULL,
    "release_date" "date" NOT NULL,
    "value" numeric NOT NULL,
    "is_preliminary" boolean DEFAULT true,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."labor_market_data_points" OWNER TO "postgres";


ALTER TABLE "public"."labor_market_data_points" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."labor_market_data_points_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE OR REPLACE VIEW "public"."labor_market_divergence_matrix" AS
 WITH "adp_raw" AS (
         SELECT "labor_market_data_points"."data_period",
            "labor_market_data_points"."value" AS "adp_level"
           FROM "public"."labor_market_data_points"
          WHERE (("labor_market_data_points"."series_id")::"text" = 'ADPMNUSNERSA'::"text")
        ), "adp_mom" AS (
         SELECT "adp_raw"."data_period",
            ("adp_raw"."adp_level" - "lag"("adp_raw"."adp_level") OVER (ORDER BY "adp_raw"."data_period")) AS "adp_new_jobs"
           FROM "adp_raw"
        ), "nfp_raw" AS (
         SELECT "labor_market_data_points"."data_period",
            "labor_market_data_points"."value" AS "nfp_level_k",
            "labor_market_data_points"."is_preliminary"
           FROM "public"."labor_market_data_points"
          WHERE (("labor_market_data_points"."series_id")::"text" = 'PAYEMS'::"text")
        ), "nfp_mom" AS (
         SELECT "nfp_raw"."data_period",
            "nfp_raw"."is_preliminary",
            (("nfp_raw"."nfp_level_k" - "lag"("nfp_raw"."nfp_level_k") OVER (ORDER BY "nfp_raw"."data_period")) * (1000)::numeric) AS "nfp_new_jobs"
           FROM "nfp_raw"
        ), "unrate" AS (
         SELECT "labor_market_data_points"."data_period",
            "labor_market_data_points"."value" AS "unrate_value"
           FROM "public"."labor_market_data_points"
          WHERE (("labor_market_data_points"."series_id")::"text" = 'UNRATE'::"text")
        ), "icsa_monthly" AS (
         SELECT ("date_trunc"('month'::"text", ("labor_market_data_points"."data_period")::timestamp with time zone))::"date" AS "data_period",
            "round"("avg"("labor_market_data_points"."value")) AS "weekly_claims_avg"
           FROM "public"."labor_market_data_points"
          WHERE (("labor_market_data_points"."series_id")::"text" = 'ICSA'::"text")
          GROUP BY (("date_trunc"('month'::"text", ("labor_market_data_points"."data_period")::timestamp with time zone))::"date")
        )
 SELECT "nfp_mom"."data_period" AS "period",
    "adp_mom"."adp_new_jobs",
    "nfp_mom"."nfp_new_jobs" AS "nfp_preliminary",
    ("nfp_mom"."nfp_new_jobs" - "adp_mom"."adp_new_jobs") AS "divergence_raw",
    "unrate"."unrate_value",
    "icsa_monthly"."weekly_claims_avg",
    "nfp_mom"."is_preliminary"
   FROM ((("nfp_mom"
     LEFT JOIN "adp_mom" ON (("nfp_mom"."data_period" = "adp_mom"."data_period")))
     LEFT JOIN "unrate" ON (("nfp_mom"."data_period" = "unrate"."data_period")))
     LEFT JOIN "icsa_monthly" ON (("nfp_mom"."data_period" = "icsa_monthly"."data_period")))
  ORDER BY "nfp_mom"."data_period" DESC;


ALTER VIEW "public"."labor_market_divergence_matrix" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."labor_market_series" (
    "id" character varying(50) NOT NULL,
    "name" character varying(100) NOT NULL,
    "category" character varying(50) NOT NULL,
    "frequency" character varying(20) NOT NULL
);


ALTER TABLE "public"."labor_market_series" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."macro_fx_rates_daily" (
    "observation_date" "date" NOT NULL,
    "currency_pair" character varying(10) NOT NULL,
    "rate" numeric,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"())
);


ALTER TABLE "public"."macro_fx_rates_daily" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."macro_global_indicator_definition" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "series_id" character varying(50) NOT NULL,
    "region" character varying(50) NOT NULL,
    "currency" character varying(10) NOT NULL,
    "description" "text",
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"())
);


ALTER TABLE "public"."macro_global_indicator_definition" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."macro_global_indicator_values" (
    "indicator_id" "uuid" NOT NULL,
    "observation_date" "date" NOT NULL,
    "raw_value" numeric,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"())
);


ALTER TABLE "public"."macro_global_indicator_values" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."macro_us_indicator_definition" (
    "id" integer NOT NULL,
    "series_id" character varying(50) NOT NULL,
    "source" character varying(50) DEFAULT 'FRED'::character varying,
    "name" character varying(255) NOT NULL,
    "frequency" character varying(20) NOT NULL,
    "beschreibung" "text"
);


ALTER TABLE "public"."macro_us_indicator_definition" OWNER TO "postgres";


ALTER TABLE "public"."macro_us_indicator_definition" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."macro_indicator_definition_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."macro_reg_alerts" (
    "document_number" character varying(100) NOT NULL,
    "publication_date" "date" NOT NULL,
    "title" "text" NOT NULL,
    "pdf_url" "text",
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()),
    "abstract" "text"
);


ALTER TABLE "public"."macro_reg_alerts" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."macro_reserve_requirements" (
    "effective_date" "date" NOT NULL,
    "ratio_percent" numeric NOT NULL,
    "document_number" character varying(100),
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"())
);


ALTER TABLE "public"."macro_reserve_requirements" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."macro_us_indicator_values" (
    "indicator_id" integer NOT NULL,
    "observation_date" "date" NOT NULL,
    "value" numeric(20,4) NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL
);


ALTER TABLE "public"."macro_us_indicator_values" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."macro_us_liquidity" (
    "observation_date" "date" NOT NULL,
    "tga_balance" numeric,
    "rrp_balance" numeric,
    "fed_balance" numeric,
    "btfp_balance" numeric,
    "updated_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()),
    "bank_reserves_fed" numeric,
    "sofr_rate" numeric
);


ALTER TABLE "public"."macro_us_liquidity" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."market_daily_candles" (
    "ticker" integer NOT NULL,
    "timestamp" integer NOT NULL,
    "open" real,
    "high" real,
    "low" real,
    "close" real,
    "volume" integer,
    "vwap" real,
    "trades" integer
);


ALTER TABLE "public"."market_daily_candles" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."market_finra_short_volume" (
    "ticker" integer NOT NULL,
    "timestamp" integer NOT NULL,
    "short_volume" bigint,
    "total_volume" bigint
);


ALTER TABLE "public"."market_finra_short_volume" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."market_m5_candles" (
    "ticker" integer NOT NULL,
    "timestamp" integer NOT NULL,
    "open" real,
    "high" real,
    "low" real,
    "close" real,
    "volume" integer,
    "vwap" real,
    "trades" integer
);


ALTER TABLE "public"."market_m5_candles" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."market_news_feed" (
    "article_link" "text" NOT NULL,
    "published_at" timestamp with time zone NOT NULL,
    "title" "text" NOT NULL,
    "tags" "jsonb",
    "sentiment_polarity" numeric,
    "inserted_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"())
);


ALTER TABLE "public"."market_news_feed" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."market_sentiment_daily" (
    "observation_date" "date" NOT NULL,
    "ticker" character varying(50) NOT NULL,
    "article_count" integer DEFAULT 0,
    "normalized_score" numeric,
    "updated_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"())
);


ALTER TABLE "public"."market_sentiment_daily" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."market_sync_queue" (
    "ticker" character varying(50) NOT NULL,
    "last_sync_at" timestamp with time zone
);


ALTER TABLE "public"."market_sync_queue" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."market_trading_days" (
    "date" "date" NOT NULL,
    "is_trading_day" boolean NOT NULL,
    "holiday_name" "text",
    "early_close" boolean DEFAULT false,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"())
);


ALTER TABLE "public"."market_trading_days" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."option_cboe_volume" (
    "ticker" integer NOT NULL,
    "timestamp" integer NOT NULL,
    "volume" integer
);


ALTER TABLE "public"."option_cboe_volume" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."option_chain_snapshots" (
    "id" bigint NOT NULL,
    "scraped_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "ticker" integer NOT NULL,
    "ticker_symbol" character varying(10) NOT NULL,
    "contract_id" character varying(30) NOT NULL,
    "expiration_date" "date" NOT NULL,
    "option_type" character varying(4) NOT NULL,
    "strike" numeric(10,2) NOT NULL,
    "volume_oi_ratio" numeric(12,4) DEFAULT 0.0000 NOT NULL,
    "volume" bigint DEFAULT 0,
    "open_interest" bigint DEFAULT 0,
    "last_price" numeric(10,2) DEFAULT 0.00,
    CONSTRAINT "option_chain_snapshots_type_check" CHECK ((("option_type")::"text" = ANY (ARRAY['CALL'::"text", 'PUT'::"text"])))
);


ALTER TABLE "public"."option_chain_snapshots" OWNER TO "postgres";


ALTER TABLE "public"."option_chain_snapshots" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."option_chain_snapshots_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."option_contract_bars" (
    "id" bigint NOT NULL,
    "ticker" integer NOT NULL,
    "contract_id" character varying(30) NOT NULL,
    "bar_timestamp" timestamp with time zone NOT NULL,
    "volume" bigint DEFAULT 0 NOT NULL,
    "open" numeric(10,4) NOT NULL,
    "high" numeric(10,4) NOT NULL,
    "low" numeric(10,4) NOT NULL,
    "close" numeric(10,4) NOT NULL,
    "vwap" numeric(10,4) NOT NULL,
    "trade_count" bigint DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."option_contract_bars" OWNER TO "postgres";


ALTER TABLE "public"."option_contract_bars" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."option_contract_bars_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."sec_ai_signals" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "filing_id" "uuid" NOT NULL,
    "ticker" character varying(10) NOT NULL,
    "signal_category" character varying(100) NOT NULL,
    "trend" "public"."ai_trend_signal" NOT NULL,
    "extracted_quote" "text" NOT NULL,
    "ai_reasoning" "text",
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "filing_date" "date"
);


ALTER TABLE "public"."sec_ai_signals" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."sec_companies" (
    "ticker" character varying(10) NOT NULL,
    "cik" character varying(10),
    "company_name" character varying(255),
    "is_foreign_issuer" boolean DEFAULT false,
    "is_active" boolean DEFAULT true,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "archetype" "public"."company_archetype"
);


ALTER TABLE "public"."sec_companies" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."sec_companies_keywords" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "ticker" character varying(10),
    "metric_name" character varying(100) NOT NULL,
    "keyword" character varying(255) NOT NULL,
    "is_active" boolean DEFAULT true,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE "public"."sec_companies_keywords" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."sec_fundamentals" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "ticker" character varying(10) NOT NULL,
    "fiscal_year" integer NOT NULL,
    "period" character varying(10) NOT NULL,
    "filing_date" "date" NOT NULL,
    "capex_actual" numeric,
    "revenue" numeric,
    "r_and_d" numeric,
    "inventory_value" numeric,
    "inventory_turnover" numeric,
    "days_sales_outstanding" numeric,
    "deferred_revenue" numeric,
    "gross_profit_margin" numeric,
    "operating_cash_flow" numeric,
    "free_cash_flow" numeric,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE "public"."sec_fundamentals" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."sec_raw_filings" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "ticker" character varying(10),
    "form_type" character varying(20) NOT NULL,
    "filing_date" "date" NOT NULL,
    "accession_number" character varying(255) NOT NULL,
    "raw_content" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE "public"."sec_raw_filings" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."sector_rotation_log" (
    "id" bigint NOT NULL,
    "datum" "date" NOT NULL,
    "ticker_id" bigint NOT NULL,
    "ticker_name" character varying(10) NOT NULL,
    "phase" character varying(50) NOT NULL,
    "adj_score" numeric(5,2) NOT NULL,
    "raw_score" numeric(5,2) NOT NULL,
    "rsi50" numeric(5,2) NOT NULL,
    "velocity" numeric(8,4) NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL
);


ALTER TABLE "public"."sector_rotation_log" OWNER TO "postgres";


ALTER TABLE "public"."sector_rotation_log" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."sector_rotation_log_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."sys_insert_logs" (
    "id" bigint NOT NULL,
    "table_name" "text" NOT NULL,
    "action_type" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."sys_insert_logs" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."sys_daily_insert_summary" AS
 SELECT "table_name",
    "sum"(
        CASE
            WHEN ("action_type" = 'INSERT'::"text") THEN 1
            ELSE 0
        END) AS "insert_count",
    "sum"(
        CASE
            WHEN ("action_type" = 'UPDATE'::"text") THEN 1
            ELSE 0
        END) AS "update_count"
   FROM "public"."sys_insert_logs"
  WHERE (("created_at" >= ((CURRENT_DATE + '00:00:00'::time without time zone) AT TIME ZONE 'Europe/Berlin'::"text")) AND ("created_at" <= ((CURRENT_DATE + '23:59:59'::time without time zone) AT TIME ZONE 'Europe/Berlin'::"text")))
  GROUP BY "table_name";


ALTER VIEW "public"."sys_daily_insert_summary" OWNER TO "postgres";


ALTER TABLE "public"."sys_insert_logs" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."sys_insert_logs_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."ticker" (
    "id" integer NOT NULL,
    "name" "text" NOT NULL,
    "company" "text" NOT NULL,
    "sector" "text",
    "ticker_typ_id" integer
);


ALTER TABLE "public"."ticker" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."ticker_data_config" (
    "ticker_id" integer NOT NULL,
    "sync_type" "public"."sync_job_type" NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"())
);


ALTER TABLE "public"."ticker_data_config" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."ticker_dependencies" (
    "id" integer NOT NULL,
    "target_ticker_id" integer,
    "macro_ticker_id" integer,
    "dependency_type" character varying(50),
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."ticker_dependencies" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."ticker_dependencies_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."ticker_dependencies_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."ticker_dependencies_id_seq" OWNED BY "public"."ticker_dependencies"."id";



ALTER TABLE "public"."ticker" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."ticker_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."ticker_typ" (
    "id" integer NOT NULL,
    "name" "text" NOT NULL
);


ALTER TABLE "public"."ticker_typ" OWNER TO "postgres";


ALTER TABLE "public"."ticker_typ" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."ticker_typ_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."treasury_auctions" (
    "cusip" character varying(50) NOT NULL,
    "auction_date" "date" NOT NULL,
    "issue_date" "date",
    "maturity_date" "date",
    "security_type" character varying(50) NOT NULL,
    "security_term" character varying(50) NOT NULL,
    "bid_to_cover_ratio" numeric,
    "high_yield" numeric,
    "total_tendered" numeric,
    "total_accepted" numeric,
    "updated_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()),
    "offering_amount" numeric,
    "primary_dealer_accepted" numeric,
    "direct_bidder_accepted" numeric,
    "indirect_bidder_accepted" numeric
);


ALTER TABLE "public"."treasury_auctions" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."treasury_qra_estimates" (
    "target_quarter" character varying(10) NOT NULL,
    "release_date" "date" NOT NULL,
    "estimated_net_borrowing" numeric,
    "estimated_tga_balance" numeric,
    "updated_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"())
);


ALTER TABLE "public"."treasury_qra_estimates" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."vw_treasury_liquidity_mix" AS
 SELECT "issue_date" AS "observation_date",
    "sum"(
        CASE
            WHEN (("security_type")::"text" = 'Bill'::"text") THEN "total_accepted"
            ELSE (0)::numeric
        END) AS "tbill_amount",
    "sum"(
        CASE
            WHEN (("security_type")::"text" = ANY (ARRAY[('Note'::character varying)::"text", ('Bond'::character varying)::"text"])) THEN "total_accepted"
            ELSE (0)::numeric
        END) AS "coupon_amount",
    "sum"("total_accepted") AS "total_issuance",
        CASE
            WHEN ("sum"("total_accepted") > (0)::numeric) THEN "round"((("sum"(
            CASE
                WHEN (("security_type")::"text" = 'Bill'::"text") THEN "total_accepted"
                ELSE (0)::numeric
            END) / "sum"("total_accepted")) * (100)::numeric), 2)
            ELSE 0.00
        END AS "tbill_ratio_percent"
   FROM "public"."treasury_auctions"
  WHERE ("issue_date" IS NOT NULL)
  GROUP BY "issue_date"
  ORDER BY "issue_date" DESC;


ALTER VIEW "public"."vw_treasury_liquidity_mix" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."vw_us_liquidity_score" AS
 SELECT "dates"."observation_date",
    "walcl"."value" AS "fed_assets",
    "tga"."value" AS "tga_balance",
    "rrp"."value" AS "rrp_balance",
    "sofr"."value" AS "sofr_rate",
    "deposits"."value" AS "deposits_all",
    "tbill"."tbill_ratio_percent",
    (("walcl"."value" - COALESCE("tga"."value", (0)::numeric)) - COALESCE("rrp"."value", (0)::numeric)) AS "fed_net_liquidity"
   FROM ((((((( SELECT DISTINCT "macro_us_indicator_values"."observation_date"
           FROM "public"."macro_us_indicator_values") "dates"
     LEFT JOIN LATERAL ( SELECT "v"."value"
           FROM ("public"."macro_us_indicator_values" "v"
             JOIN "public"."macro_us_indicator_definition" "d" ON (("v"."indicator_id" = "d"."id")))
          WHERE ((("d"."series_id")::"text" = 'WALCL'::"text") AND ("v"."observation_date" <= "dates"."observation_date"))
          ORDER BY "v"."observation_date" DESC
         LIMIT 1) "walcl" ON (true))
     LEFT JOIN LATERAL ( SELECT "v"."value"
           FROM ("public"."macro_us_indicator_values" "v"
             JOIN "public"."macro_us_indicator_definition" "d" ON (("v"."indicator_id" = "d"."id")))
          WHERE ((("d"."series_id")::"text" = 'WTREGEN'::"text") AND ("v"."observation_date" <= "dates"."observation_date"))
          ORDER BY "v"."observation_date" DESC
         LIMIT 1) "tga" ON (true))
     LEFT JOIN LATERAL ( SELECT "v"."value"
           FROM ("public"."macro_us_indicator_values" "v"
             JOIN "public"."macro_us_indicator_definition" "d" ON (("v"."indicator_id" = "d"."id")))
          WHERE ((("d"."series_id")::"text" = 'RRPONTSYD'::"text") AND ("v"."observation_date" <= "dates"."observation_date"))
          ORDER BY "v"."observation_date" DESC
         LIMIT 1) "rrp" ON (true))
     LEFT JOIN LATERAL ( SELECT "v"."value"
           FROM ("public"."macro_us_indicator_values" "v"
             JOIN "public"."macro_us_indicator_definition" "d" ON (("v"."indicator_id" = "d"."id")))
          WHERE ((("d"."series_id")::"text" = 'SOFR'::"text") AND ("v"."observation_date" <= "dates"."observation_date"))
          ORDER BY "v"."observation_date" DESC
         LIMIT 1) "sofr" ON (true))
     LEFT JOIN LATERAL ( SELECT "v"."value"
           FROM ("public"."macro_us_indicator_values" "v"
             JOIN "public"."macro_us_indicator_definition" "d" ON (("v"."indicator_id" = "d"."id")))
          WHERE ((("d"."series_id")::"text" = 'DPSACBW027SBOG'::"text") AND ("v"."observation_date" <= "dates"."observation_date"))
          ORDER BY "v"."observation_date" DESC
         LIMIT 1) "deposits" ON (true))
     LEFT JOIN LATERAL ( SELECT "t"."tbill_ratio_percent"
           FROM "public"."vw_treasury_liquidity_mix" "t"
          WHERE ("t"."observation_date" <= "dates"."observation_date")
          ORDER BY "t"."observation_date" DESC
         LIMIT 1) "tbill" ON (true))
  ORDER BY "dates"."observation_date" DESC;


ALTER VIEW "public"."vw_us_liquidity_score" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."vw_global_liquidity_score" AS
 WITH "global_dates" AS (
         SELECT "macro_us_indicator_values"."observation_date"
           FROM "public"."macro_us_indicator_values"
        UNION
         SELECT "macro_global_indicator_values"."observation_date"
           FROM "public"."macro_global_indicator_values"
        ), "daily_data" AS (
         SELECT "d"."observation_date",
            "us"."fed_net_liquidity",
            ( SELECT "v"."raw_value"
                   FROM ("public"."macro_global_indicator_values" "v"
                     JOIN "public"."macro_global_indicator_definition" "def" ON (("v"."indicator_id" = "def"."id")))
                  WHERE ((("def"."series_id")::"text" = 'ECBASSETSW'::"text") AND ("v"."observation_date" <= "d"."observation_date"))
                  ORDER BY "v"."observation_date" DESC
                 LIMIT 1) AS "ecb_assets_eur",
            ( SELECT "v"."raw_value"
                   FROM ("public"."macro_global_indicator_values" "v"
                     JOIN "public"."macro_global_indicator_definition" "def" ON (("v"."indicator_id" = "def"."id")))
                  WHERE ((("def"."series_id")::"text" = 'JPNASSETS'::"text") AND ("v"."observation_date" <= "d"."observation_date"))
                  ORDER BY "v"."observation_date" DESC
                 LIMIT 1) AS "boj_assets_jpy_100m",
            ( SELECT "v"."raw_value"
                   FROM ("public"."macro_global_indicator_values" "v"
                     JOIN "public"."macro_global_indicator_definition" "def" ON (("v"."indicator_id" = "def"."id")))
                  WHERE ((("def"."series_id")::"text" = 'WLRRAFOIAL'::"text") AND ("v"."observation_date" <= "d"."observation_date"))
                  ORDER BY "v"."observation_date" DESC
                 LIMIT 1) AS "foreign_repo_usd",
            ( SELECT "fx"."rate"
                   FROM "public"."macro_fx_rates_daily" "fx"
                  WHERE ((("fx"."currency_pair")::"text" = 'EURUSD'::"text") AND ("fx"."observation_date" <= "d"."observation_date"))
                  ORDER BY "fx"."observation_date" DESC
                 LIMIT 1) AS "eurusd_rate",
            ( SELECT "fx"."rate"
                   FROM "public"."macro_fx_rates_daily" "fx"
                  WHERE ((("fx"."currency_pair")::"text" = 'USDJPY'::"text") AND ("fx"."observation_date" <= "d"."observation_date"))
                  ORDER BY "fx"."observation_date" DESC
                 LIMIT 1) AS "usdjpy_rate"
           FROM ("global_dates" "d"
             LEFT JOIN "public"."vw_us_liquidity_score" "us" ON (("d"."observation_date" = "us"."observation_date")))
        )
 SELECT "observation_date",
    "fed_net_liquidity",
    ("ecb_assets_eur" * "eurusd_rate") AS "ecb_assets_usd",
    (("boj_assets_jpy_100m" * (100)::numeric) / NULLIF("usdjpy_rate", (0)::numeric)) AS "boj_assets_usd",
    "foreign_repo_usd",
    (((COALESCE("fed_net_liquidity", (0)::numeric) + COALESCE(("ecb_assets_eur" * "eurusd_rate"), (0)::numeric)) + COALESCE((("boj_assets_jpy_100m" * (100)::numeric) / NULLIF("usdjpy_rate", (0)::numeric)), (0)::numeric)) - COALESCE("foreign_repo_usd", (0)::numeric)) AS "global_net_liquidity_usd"
   FROM "daily_data"
  ORDER BY "observation_date" DESC;


ALTER VIEW "public"."vw_global_liquidity_score" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."vw_global_liquidity_ampel" AS
 WITH "global_momentum" AS (
         SELECT "vw_global_liquidity_score"."observation_date",
            "vw_global_liquidity_score"."global_net_liquidity_usd",
            "lag"("vw_global_liquidity_score"."global_net_liquidity_usd", 14) OVER (ORDER BY "vw_global_liquidity_score"."observation_date") AS "liq_14d_ago"
           FROM "public"."vw_global_liquidity_score"
        ), "daily_options" AS (
         SELECT "date"("option_chain_snapshots"."scraped_at") AS "obs_date",
                CASE
                    WHEN ("sum"(
                    CASE
                        WHEN (("option_chain_snapshots"."option_type")::"text" = 'CALL'::"text") THEN "option_chain_snapshots"."volume"
                        ELSE (0)::bigint
                    END) > (0)::numeric) THEN "round"(("sum"(
                    CASE
                        WHEN (("option_chain_snapshots"."option_type")::"text" = 'PUT'::"text") THEN "option_chain_snapshots"."volume"
                        ELSE (0)::bigint
                    END) / "sum"(
                    CASE
                        WHEN (("option_chain_snapshots"."option_type")::"text" = 'CALL'::"text") THEN "option_chain_snapshots"."volume"
                        ELSE (0)::bigint
                    END)), 2)
                    ELSE 1.00
                END AS "put_call_ratio"
           FROM "public"."option_chain_snapshots"
          GROUP BY ("date"("option_chain_snapshots"."scraped_at"))
        )
 SELECT "g"."observation_date",
    "g"."global_net_liquidity_usd",
    ("g"."global_net_liquidity_usd" - "g"."liq_14d_ago") AS "liq_momentum_14d",
    COALESCE("o"."put_call_ratio", 1.00) AS "put_call_ratio",
        CASE
            WHEN ((("g"."global_net_liquidity_usd" - "g"."liq_14d_ago") <= ('-100000'::integer)::numeric) AND (COALESCE("o"."put_call_ratio", 1.00) >= 1.10)) THEN 'ROT (Struktureller Drain / Hedgen)'::"text"
            WHEN ((("g"."global_net_liquidity_usd" - "g"."liq_14d_ago") < (0)::numeric) OR (COALESCE("o"."put_call_ratio", 1.00) >= 1.00)) THEN 'GELB (Vorsicht / Warnstufe)'::"text"
            ELSE 'GRÜN (Risk On / Expansion)'::"text"
        END AS "global_ampel_status"
   FROM ("global_momentum" "g"
     LEFT JOIN "daily_options" "o" ON (("g"."observation_date" = "o"."obs_date")))
  ORDER BY "g"."observation_date" DESC;


ALTER VIEW "public"."vw_global_liquidity_ampel" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."vw_liquidity_ampel" AS
 WITH "daily_options" AS (
         SELECT "date"("option_chain_snapshots"."scraped_at") AS "obs_date",
            "sum"(
                CASE
                    WHEN (("option_chain_snapshots"."option_type")::"text" = 'PUT'::"text") THEN "option_chain_snapshots"."volume"
                    ELSE (0)::bigint
                END) AS "put_volume",
            "sum"(
                CASE
                    WHEN (("option_chain_snapshots"."option_type")::"text" = 'CALL'::"text") THEN "option_chain_snapshots"."volume"
                    ELSE (0)::bigint
                END) AS "call_volume",
                CASE
                    WHEN ("sum"(
                    CASE
                        WHEN (("option_chain_snapshots"."option_type")::"text" = 'CALL'::"text") THEN "option_chain_snapshots"."volume"
                        ELSE (0)::bigint
                    END) > (0)::numeric) THEN "round"(("sum"(
                    CASE
                        WHEN (("option_chain_snapshots"."option_type")::"text" = 'PUT'::"text") THEN "option_chain_snapshots"."volume"
                        ELSE (0)::bigint
                    END) / "sum"(
                    CASE
                        WHEN (("option_chain_snapshots"."option_type")::"text" = 'CALL'::"text") THEN "option_chain_snapshots"."volume"
                        ELSE (0)::bigint
                    END)), 2)
                    ELSE 1.00
                END AS "put_call_ratio"
           FROM "public"."option_chain_snapshots"
          GROUP BY ("date"("option_chain_snapshots"."scraped_at"))
        ), "liquidity_momentum" AS (
         SELECT "vw_us_liquidity_score"."observation_date",
            "vw_us_liquidity_score"."fed_net_liquidity",
            "vw_us_liquidity_score"."tga_balance",
            "lag"("vw_us_liquidity_score"."fed_net_liquidity", 5) OVER (ORDER BY "vw_us_liquidity_score"."observation_date") AS "liq_5d_ago"
           FROM "public"."vw_us_liquidity_score"
        )
 SELECT "l"."observation_date",
    "l"."fed_net_liquidity",
    ("l"."fed_net_liquidity" - "l"."liq_5d_ago") AS "liq_momentum_5d",
    COALESCE("o"."put_call_ratio", 1.00) AS "put_call_ratio",
        CASE
            WHEN ((("l"."fed_net_liquidity" - "l"."liq_5d_ago") < ('-50000'::integer)::numeric) AND (COALESCE("o"."put_call_ratio", 1.00) > 1.10)) THEN 'ROT (Raus hier / Hedgen)'::"text"
            WHEN ((("l"."fed_net_liquidity" - "l"."liq_5d_ago") < (0)::numeric) OR (COALESCE("o"."put_call_ratio", 1.00) > 1.00)) THEN 'GELB (Vorsicht / Stop Loss anpassen)'::"text"
            ELSE 'GRÜN (Risk On)'::"text"
        END AS "ampel_status"
   FROM ("liquidity_momentum" "l"
     LEFT JOIN "daily_options" "o" ON (("l"."observation_date" = "o"."obs_date")))
  ORDER BY "l"."observation_date" DESC;


ALTER VIEW "public"."vw_liquidity_ampel" OWNER TO "postgres";


ALTER TABLE ONLY "public"."ticker_dependencies" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."ticker_dependencies_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."labor_market_data_points"
    ADD CONSTRAINT "labor_market_data_points_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."labor_market_data_points"
    ADD CONSTRAINT "labor_market_data_points_series_period_key" UNIQUE ("series_id", "data_period");



ALTER TABLE ONLY "public"."labor_market_series"
    ADD CONSTRAINT "labor_market_series_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."macro_fx_rates_daily"
    ADD CONSTRAINT "macro_fx_rates_daily_pkey" PRIMARY KEY ("observation_date", "currency_pair");



ALTER TABLE ONLY "public"."macro_global_indicator_definition"
    ADD CONSTRAINT "macro_global_indicator_definition_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."macro_global_indicator_definition"
    ADD CONSTRAINT "macro_global_indicator_definition_series_id_key" UNIQUE ("series_id");



ALTER TABLE ONLY "public"."macro_global_indicator_values"
    ADD CONSTRAINT "macro_global_indicator_values_pkey" PRIMARY KEY ("indicator_id", "observation_date");



ALTER TABLE ONLY "public"."macro_reg_alerts"
    ADD CONSTRAINT "macro_reg_alerts_pkey" PRIMARY KEY ("document_number");



ALTER TABLE ONLY "public"."macro_reserve_requirements"
    ADD CONSTRAINT "macro_reserve_requirements_pkey" PRIMARY KEY ("effective_date");



ALTER TABLE ONLY "public"."macro_us_indicator_definition"
    ADD CONSTRAINT "macro_us_indicator_definition_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."macro_us_indicator_values"
    ADD CONSTRAINT "macro_us_indicator_values_pkey" PRIMARY KEY ("indicator_id", "observation_date");



ALTER TABLE ONLY "public"."macro_us_liquidity"
    ADD CONSTRAINT "macro_us_liquidity_pkey" PRIMARY KEY ("observation_date");



ALTER TABLE ONLY "public"."market_daily_candles"
    ADD CONSTRAINT "market_daily_candles_pkey" PRIMARY KEY ("ticker", "timestamp");



ALTER TABLE ONLY "public"."market_event_calendar"
    ADD CONSTRAINT "market_event_calendar_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."market_finra_short_volume"
    ADD CONSTRAINT "market_finra_short_volume_pkey" PRIMARY KEY ("ticker", "timestamp");



ALTER TABLE ONLY "public"."market_m5_candles"
    ADD CONSTRAINT "market_m5_candles_pkey" PRIMARY KEY ("ticker", "timestamp");



ALTER TABLE ONLY "public"."market_news_feed"
    ADD CONSTRAINT "market_news_feed_pkey" PRIMARY KEY ("article_link");



ALTER TABLE ONLY "public"."market_sentiment_daily"
    ADD CONSTRAINT "market_sentiment_daily_pkey" PRIMARY KEY ("observation_date", "ticker");



ALTER TABLE ONLY "public"."market_sync_queue"
    ADD CONSTRAINT "market_sync_queue_pkey" PRIMARY KEY ("ticker");



ALTER TABLE ONLY "public"."market_trading_days"
    ADD CONSTRAINT "market_trading_days_pkey" PRIMARY KEY ("date");



ALTER TABLE ONLY "public"."option_cboe_volume"
    ADD CONSTRAINT "option_cboe_volume_pkey" PRIMARY KEY ("ticker", "timestamp");



ALTER TABLE ONLY "public"."option_chain_snapshots"
    ADD CONSTRAINT "option_chain_snapshots_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."option_contract_bars"
    ADD CONSTRAINT "option_contract_bars_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."sec_ai_signals"
    ADD CONSTRAINT "sec_ai_signals_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."sec_companies_keywords"
    ADD CONSTRAINT "sec_companies_keywords_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."sec_companies_keywords"
    ADD CONSTRAINT "sec_companies_keywords_ticker_metric_name_keyword_key" UNIQUE ("ticker", "metric_name", "keyword");



ALTER TABLE ONLY "public"."sec_companies"
    ADD CONSTRAINT "sec_companies_pkey" PRIMARY KEY ("ticker");



ALTER TABLE ONLY "public"."sec_fundamentals"
    ADD CONSTRAINT "sec_fundamentals_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."sec_raw_filings"
    ADD CONSTRAINT "sec_raw_filings_accession_number_key" UNIQUE ("accession_number");



ALTER TABLE ONLY "public"."sec_raw_filings"
    ADD CONSTRAINT "sec_raw_filings_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."sector_rotation_log"
    ADD CONSTRAINT "sector_rotation_log_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."sys_insert_logs"
    ADD CONSTRAINT "sys_insert_logs_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."ticker_data_config"
    ADD CONSTRAINT "ticker_data_config_pkey" PRIMARY KEY ("ticker_id", "sync_type");



ALTER TABLE ONLY "public"."ticker_dependencies"
    ADD CONSTRAINT "ticker_dependencies_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."ticker"
    ADD CONSTRAINT "ticker_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."ticker_typ"
    ADD CONSTRAINT "ticker_typ_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."ticker_typ"
    ADD CONSTRAINT "ticker_typ_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."treasury_auctions"
    ADD CONSTRAINT "treasury_auctions_pkey" PRIMARY KEY ("cusip");



ALTER TABLE ONLY "public"."treasury_qra_estimates"
    ADD CONSTRAINT "treasury_qra_estimates_pkey" PRIMARY KEY ("target_quarter", "release_date");



ALTER TABLE ONLY "public"."option_chain_snapshots"
    ADD CONSTRAINT "unique_chain_snapshot_entry" UNIQUE ("contract_id", "scraped_at");



ALTER TABLE ONLY "public"."option_contract_bars"
    ADD CONSTRAINT "unique_contract_bar_entry" UNIQUE ("contract_id", "bar_timestamp");



ALTER TABLE ONLY "public"."sector_rotation_log"
    ADD CONSTRAINT "unique_daily_sector_log" UNIQUE ("datum", "ticker_id");



ALTER TABLE ONLY "public"."market_event_calendar"
    ADD CONSTRAINT "unique_ticker_event" UNIQUE ("ticker_id", "event_typ", "event_datum");



ALTER TABLE ONLY "public"."macro_us_indicator_definition"
    ADD CONSTRAINT "unique_us_series_id" UNIQUE ("series_id");



CREATE INDEX "idx_ai_signals_ticker_trend" ON "public"."sec_ai_signals" USING "btree" ("ticker", "trend");



CREATE INDEX "idx_contract_bars_lookup" ON "public"."option_contract_bars" USING "btree" ("contract_id", "bar_timestamp");



CREATE INDEX "idx_event_calendar_datum" ON "public"."market_event_calendar" USING "btree" ("event_datum");



CREATE INDEX "idx_event_calendar_ticker" ON "public"."market_event_calendar" USING "btree" ("ticker_name");



CREATE INDEX "idx_fmp_ticker_date" ON "public"."sec_fundamentals" USING "btree" ("ticker", "filing_date" DESC);



CREATE INDEX "idx_fx_rates_date" ON "public"."macro_fx_rates_daily" USING "btree" ("observation_date");



CREATE INDEX "idx_labor_market_data_lookup" ON "public"."labor_market_data_points" USING "btree" ("series_id", "data_period");



CREATE INDEX "idx_macro_global_date" ON "public"."macro_global_indicator_values" USING "btree" ("observation_date");



CREATE INDEX "idx_macro_us_values_date" ON "public"."macro_us_indicator_values" USING "btree" ("observation_date" DESC);



CREATE INDEX "idx_option_chain_ratio_trigger" ON "public"."option_chain_snapshots" USING "btree" ("volume_oi_ratio") WHERE ("volume_oi_ratio" > 1.0);



CREATE INDEX "idx_option_chain_ticker_id_time" ON "public"."option_chain_snapshots" USING "btree" ("ticker", "scraped_at" DESC);



CREATE INDEX "idx_sec_keywords_ticker" ON "public"."sec_companies_keywords" USING "btree" ("ticker");



CREATE INDEX "idx_sec_raw_ticker" ON "public"."sec_raw_filings" USING "btree" ("ticker");



CREATE INDEX "idx_sector_log_datum" ON "public"."sector_rotation_log" USING "btree" ("datum");



CREATE INDEX "idx_sector_log_ticker" ON "public"."sector_rotation_log" USING "btree" ("ticker_name");



CREATE INDEX "idx_sys_insert_logs_created_at" ON "public"."sys_insert_logs" USING "btree" ("created_at");



CREATE INDEX "idx_ticker_config_sync_type" ON "public"."ticker_data_config" USING "btree" ("sync_type") WHERE ("is_active" = true);



CREATE OR REPLACE TRIGGER "tr_sys_labor_market_data_points" AFTER INSERT OR UPDATE ON "public"."labor_market_data_points" FOR EACH ROW EXECUTE FUNCTION "public"."sys_log_table_operation"();



CREATE OR REPLACE TRIGGER "tr_sys_macro_fx_rates_daily" AFTER INSERT OR UPDATE ON "public"."macro_fx_rates_daily" FOR EACH ROW EXECUTE FUNCTION "public"."sys_log_table_operation"();



CREATE OR REPLACE TRIGGER "tr_sys_macro_global_indicator_values" AFTER INSERT OR UPDATE ON "public"."macro_global_indicator_values" FOR EACH ROW EXECUTE FUNCTION "public"."sys_log_table_operation"();



CREATE OR REPLACE TRIGGER "tr_sys_macro_reg_alerts" AFTER INSERT ON "public"."macro_reg_alerts" FOR EACH ROW EXECUTE FUNCTION "public"."sys_log_table_operation"();



CREATE OR REPLACE TRIGGER "tr_sys_macro_reserve_requirements" AFTER INSERT ON "public"."macro_reserve_requirements" FOR EACH ROW EXECUTE FUNCTION "public"."sys_log_table_operation"();



CREATE OR REPLACE TRIGGER "tr_sys_macro_us_indicator_values" AFTER INSERT OR UPDATE ON "public"."macro_us_indicator_values" FOR EACH ROW EXECUTE FUNCTION "public"."sys_log_table_operation"();



CREATE OR REPLACE TRIGGER "tr_sys_macro_us_liquidity" AFTER INSERT OR UPDATE ON "public"."macro_us_liquidity" FOR EACH ROW EXECUTE FUNCTION "public"."sys_log_table_operation"();



CREATE OR REPLACE TRIGGER "tr_sys_market_daily_candles" AFTER INSERT OR UPDATE ON "public"."market_daily_candles" FOR EACH ROW EXECUTE FUNCTION "public"."sys_log_table_operation"();



CREATE OR REPLACE TRIGGER "tr_sys_market_event_calendar" AFTER INSERT OR UPDATE ON "public"."market_event_calendar" FOR EACH ROW EXECUTE FUNCTION "public"."sys_log_table_operation"();



CREATE OR REPLACE TRIGGER "tr_sys_market_finra_short_volume" AFTER INSERT OR UPDATE ON "public"."market_finra_short_volume" FOR EACH ROW EXECUTE FUNCTION "public"."sys_log_table_operation"();



CREATE OR REPLACE TRIGGER "tr_sys_market_m5_candles" AFTER INSERT OR UPDATE ON "public"."market_m5_candles" FOR EACH ROW EXECUTE FUNCTION "public"."sys_log_table_operation"();



CREATE OR REPLACE TRIGGER "tr_sys_market_news_feed" AFTER INSERT OR UPDATE ON "public"."market_news_feed" FOR EACH ROW EXECUTE FUNCTION "public"."sys_log_table_operation"();



CREATE OR REPLACE TRIGGER "tr_sys_market_sentiment_daily" AFTER INSERT OR UPDATE ON "public"."market_sentiment_daily" FOR EACH ROW EXECUTE FUNCTION "public"."sys_log_table_operation"();



CREATE OR REPLACE TRIGGER "tr_sys_market_sync_queue" AFTER INSERT OR UPDATE ON "public"."market_sync_queue" FOR EACH ROW EXECUTE FUNCTION "public"."sys_log_table_operation"();



CREATE OR REPLACE TRIGGER "tr_sys_option_cboe_volume" AFTER INSERT OR UPDATE ON "public"."option_cboe_volume" FOR EACH ROW EXECUTE FUNCTION "public"."sys_log_table_operation"();



CREATE OR REPLACE TRIGGER "tr_sys_option_chain_snapshots" AFTER INSERT OR UPDATE ON "public"."option_chain_snapshots" FOR EACH ROW EXECUTE FUNCTION "public"."sys_log_table_operation"();



CREATE OR REPLACE TRIGGER "tr_sys_option_contract_bars" AFTER INSERT OR UPDATE ON "public"."option_contract_bars" FOR EACH ROW EXECUTE FUNCTION "public"."sys_log_table_operation"();



CREATE OR REPLACE TRIGGER "tr_sys_sec_ai_signals" AFTER INSERT ON "public"."sec_ai_signals" FOR EACH ROW EXECUTE FUNCTION "public"."sys_log_table_operation"();



CREATE OR REPLACE TRIGGER "tr_sys_sec_companies" AFTER UPDATE ON "public"."sec_companies" FOR EACH ROW EXECUTE FUNCTION "public"."sys_log_table_operation"();



CREATE OR REPLACE TRIGGER "tr_sys_sec_fundamentals" AFTER INSERT ON "public"."sec_fundamentals" FOR EACH ROW EXECUTE FUNCTION "public"."sys_log_table_operation"();



CREATE OR REPLACE TRIGGER "tr_sys_sec_raw_filings" AFTER INSERT ON "public"."sec_raw_filings" FOR EACH ROW EXECUTE FUNCTION "public"."sys_log_table_operation"();



CREATE OR REPLACE TRIGGER "tr_sys_sector_rotation_log" AFTER INSERT OR UPDATE ON "public"."sector_rotation_log" FOR EACH ROW EXECUTE FUNCTION "public"."sys_log_table_operation"();



CREATE OR REPLACE TRIGGER "tr_sys_treasury_auctions" AFTER INSERT OR UPDATE ON "public"."treasury_auctions" FOR EACH ROW EXECUTE FUNCTION "public"."sys_log_table_operation"();



CREATE OR REPLACE TRIGGER "tr_sys_treasury_qra_estimates" AFTER INSERT OR UPDATE ON "public"."treasury_qra_estimates" FOR EACH ROW EXECUTE FUNCTION "public"."sys_log_table_operation"();



ALTER TABLE ONLY "public"."market_event_calendar"
    ADD CONSTRAINT "event_calendar_ticker_id_fkey" FOREIGN KEY ("ticker_id") REFERENCES "public"."ticker"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."option_cboe_volume"
    ADD CONSTRAINT "fk_cboe_options_volume_ticker" FOREIGN KEY ("ticker") REFERENCES "public"."ticker"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."market_finra_short_volume"
    ADD CONSTRAINT "fk_finra_short_volume_ticker" FOREIGN KEY ("ticker") REFERENCES "public"."ticker"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."market_m5_candles"
    ADD CONSTRAINT "fk_m5_candles_ticker" FOREIGN KEY ("ticker") REFERENCES "public"."ticker"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."macro_us_indicator_values"
    ADD CONSTRAINT "fk_macro_us_values_indicator" FOREIGN KEY ("indicator_id") REFERENCES "public"."macro_us_indicator_definition"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."market_daily_candles"
    ADD CONSTRAINT "fk_market_daily_candles_ticker" FOREIGN KEY ("ticker") REFERENCES "public"."ticker"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."option_chain_snapshots"
    ADD CONSTRAINT "fk_option_chain_ticker" FOREIGN KEY ("ticker") REFERENCES "public"."ticker"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."option_contract_bars"
    ADD CONSTRAINT "fk_option_contract_bars_ticker" FOREIGN KEY ("ticker") REFERENCES "public"."ticker"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."labor_market_data_points"
    ADD CONSTRAINT "labor_market_data_points_series_id_fkey" FOREIGN KEY ("series_id") REFERENCES "public"."labor_market_series"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."macro_global_indicator_values"
    ADD CONSTRAINT "macro_global_indicator_values_indicator_id_fkey" FOREIGN KEY ("indicator_id") REFERENCES "public"."macro_global_indicator_definition"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."sec_ai_signals"
    ADD CONSTRAINT "sec_ai_signals_filing_id_fkey" FOREIGN KEY ("filing_id") REFERENCES "public"."sec_raw_filings"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."sec_ai_signals"
    ADD CONSTRAINT "sec_ai_signals_ticker_fkey" FOREIGN KEY ("ticker") REFERENCES "public"."sec_companies"("ticker") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."sec_companies_keywords"
    ADD CONSTRAINT "sec_companies_keywords_ticker_fkey" FOREIGN KEY ("ticker") REFERENCES "public"."sec_companies"("ticker") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."sec_fundamentals"
    ADD CONSTRAINT "sec_fmp_fundamentals_ticker_fkey" FOREIGN KEY ("ticker") REFERENCES "public"."sec_companies"("ticker") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."sec_raw_filings"
    ADD CONSTRAINT "sec_raw_filings_ticker_fkey" FOREIGN KEY ("ticker") REFERENCES "public"."sec_companies"("ticker") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."sector_rotation_log"
    ADD CONSTRAINT "sector_rotation_log_ticker_id_fkey" FOREIGN KEY ("ticker_id") REFERENCES "public"."ticker"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."ticker_data_config"
    ADD CONSTRAINT "ticker_data_config_ticker_id_fkey" FOREIGN KEY ("ticker_id") REFERENCES "public"."ticker"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."ticker_dependencies"
    ADD CONSTRAINT "ticker_dependencies_macro_ticker_id_fkey" FOREIGN KEY ("macro_ticker_id") REFERENCES "public"."ticker"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."ticker_dependencies"
    ADD CONSTRAINT "ticker_dependencies_target_ticker_id_fkey" FOREIGN KEY ("target_ticker_id") REFERENCES "public"."ticker"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."ticker"
    ADD CONSTRAINT "ticker_ticker_typ_id_fkey" FOREIGN KEY ("ticker_typ_id") REFERENCES "public"."ticker_typ"("id") ON DELETE SET NULL;



CREATE POLICY "Allow insert/update for service role" ON "public"."market_trading_days" USING (("auth"."role"() = 'service_role'::"text"));



CREATE POLICY "Allow read access for all users" ON "public"."market_trading_days" FOR SELECT USING (true);



ALTER TABLE "public"."labor_market_data_points" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."labor_market_series" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."macro_fx_rates_daily" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."macro_global_indicator_definition" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."macro_global_indicator_values" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."macro_reg_alerts" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."macro_reserve_requirements" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."macro_us_indicator_definition" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."macro_us_indicator_values" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."macro_us_liquidity" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."market_daily_candles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."market_event_calendar" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."market_finra_short_volume" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."market_m5_candles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."market_news_feed" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."market_sentiment_daily" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."market_sync_queue" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."market_trading_days" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."option_cboe_volume" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."option_chain_snapshots" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."option_contract_bars" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."sec_ai_signals" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."sec_companies" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."sec_companies_keywords" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."sec_fundamentals" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."sec_raw_filings" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."sector_rotation_log" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."sys_insert_logs" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."ticker" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."ticker_data_config" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."ticker_dependencies" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."ticker_typ" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."treasury_auctions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."treasury_qra_estimates" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";





GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";











































































































































































GRANT ALL ON FUNCTION "public"."get_missing_sentiment_dates"("target_ticker" "text", "start_date" "date", "exclude_weekends" boolean) TO "anon";
GRANT ALL ON FUNCTION "public"."get_missing_sentiment_dates"("target_ticker" "text", "start_date" "date", "exclude_weekends" boolean) TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_missing_sentiment_dates"("target_ticker" "text", "start_date" "date", "exclude_weekends" boolean) TO "service_role";



GRANT ALL ON FUNCTION "public"."sys_log_table_operation"() TO "anon";
GRANT ALL ON FUNCTION "public"."sys_log_table_operation"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."sys_log_table_operation"() TO "service_role";
























GRANT ALL ON TABLE "public"."market_event_calendar" TO "anon";
GRANT ALL ON TABLE "public"."market_event_calendar" TO "authenticated";
GRANT ALL ON TABLE "public"."market_event_calendar" TO "service_role";



GRANT ALL ON SEQUENCE "public"."event_calendar_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."event_calendar_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."event_calendar_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."labor_market_data_points" TO "anon";
GRANT ALL ON TABLE "public"."labor_market_data_points" TO "authenticated";
GRANT ALL ON TABLE "public"."labor_market_data_points" TO "service_role";



GRANT ALL ON SEQUENCE "public"."labor_market_data_points_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."labor_market_data_points_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."labor_market_data_points_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."labor_market_divergence_matrix" TO "anon";
GRANT ALL ON TABLE "public"."labor_market_divergence_matrix" TO "authenticated";
GRANT ALL ON TABLE "public"."labor_market_divergence_matrix" TO "service_role";



GRANT ALL ON TABLE "public"."labor_market_series" TO "anon";
GRANT ALL ON TABLE "public"."labor_market_series" TO "authenticated";
GRANT ALL ON TABLE "public"."labor_market_series" TO "service_role";



GRANT ALL ON TABLE "public"."macro_fx_rates_daily" TO "anon";
GRANT ALL ON TABLE "public"."macro_fx_rates_daily" TO "authenticated";
GRANT ALL ON TABLE "public"."macro_fx_rates_daily" TO "service_role";



GRANT ALL ON TABLE "public"."macro_global_indicator_definition" TO "anon";
GRANT ALL ON TABLE "public"."macro_global_indicator_definition" TO "authenticated";
GRANT ALL ON TABLE "public"."macro_global_indicator_definition" TO "service_role";



GRANT ALL ON TABLE "public"."macro_global_indicator_values" TO "anon";
GRANT ALL ON TABLE "public"."macro_global_indicator_values" TO "authenticated";
GRANT ALL ON TABLE "public"."macro_global_indicator_values" TO "service_role";



GRANT ALL ON TABLE "public"."macro_us_indicator_definition" TO "anon";
GRANT ALL ON TABLE "public"."macro_us_indicator_definition" TO "authenticated";
GRANT ALL ON TABLE "public"."macro_us_indicator_definition" TO "service_role";



GRANT ALL ON SEQUENCE "public"."macro_indicator_definition_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."macro_indicator_definition_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."macro_indicator_definition_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."macro_reg_alerts" TO "anon";
GRANT ALL ON TABLE "public"."macro_reg_alerts" TO "authenticated";
GRANT ALL ON TABLE "public"."macro_reg_alerts" TO "service_role";



GRANT ALL ON TABLE "public"."macro_reserve_requirements" TO "anon";
GRANT ALL ON TABLE "public"."macro_reserve_requirements" TO "authenticated";
GRANT ALL ON TABLE "public"."macro_reserve_requirements" TO "service_role";



GRANT ALL ON TABLE "public"."macro_us_indicator_values" TO "anon";
GRANT ALL ON TABLE "public"."macro_us_indicator_values" TO "authenticated";
GRANT ALL ON TABLE "public"."macro_us_indicator_values" TO "service_role";



GRANT ALL ON TABLE "public"."macro_us_liquidity" TO "anon";
GRANT ALL ON TABLE "public"."macro_us_liquidity" TO "authenticated";
GRANT ALL ON TABLE "public"."macro_us_liquidity" TO "service_role";



GRANT ALL ON TABLE "public"."market_daily_candles" TO "anon";
GRANT ALL ON TABLE "public"."market_daily_candles" TO "authenticated";
GRANT ALL ON TABLE "public"."market_daily_candles" TO "service_role";



GRANT ALL ON TABLE "public"."market_finra_short_volume" TO "anon";
GRANT ALL ON TABLE "public"."market_finra_short_volume" TO "authenticated";
GRANT ALL ON TABLE "public"."market_finra_short_volume" TO "service_role";



GRANT ALL ON TABLE "public"."market_m5_candles" TO "anon";
GRANT ALL ON TABLE "public"."market_m5_candles" TO "authenticated";
GRANT ALL ON TABLE "public"."market_m5_candles" TO "service_role";



GRANT ALL ON TABLE "public"."market_news_feed" TO "anon";
GRANT ALL ON TABLE "public"."market_news_feed" TO "authenticated";
GRANT ALL ON TABLE "public"."market_news_feed" TO "service_role";



GRANT ALL ON TABLE "public"."market_sentiment_daily" TO "anon";
GRANT ALL ON TABLE "public"."market_sentiment_daily" TO "authenticated";
GRANT ALL ON TABLE "public"."market_sentiment_daily" TO "service_role";



GRANT ALL ON TABLE "public"."market_sync_queue" TO "anon";
GRANT ALL ON TABLE "public"."market_sync_queue" TO "authenticated";
GRANT ALL ON TABLE "public"."market_sync_queue" TO "service_role";



GRANT ALL ON TABLE "public"."market_trading_days" TO "anon";
GRANT ALL ON TABLE "public"."market_trading_days" TO "authenticated";
GRANT ALL ON TABLE "public"."market_trading_days" TO "service_role";



GRANT ALL ON TABLE "public"."option_cboe_volume" TO "anon";
GRANT ALL ON TABLE "public"."option_cboe_volume" TO "authenticated";
GRANT ALL ON TABLE "public"."option_cboe_volume" TO "service_role";



GRANT ALL ON TABLE "public"."option_chain_snapshots" TO "anon";
GRANT ALL ON TABLE "public"."option_chain_snapshots" TO "authenticated";
GRANT ALL ON TABLE "public"."option_chain_snapshots" TO "service_role";



GRANT ALL ON SEQUENCE "public"."option_chain_snapshots_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."option_chain_snapshots_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."option_chain_snapshots_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."option_contract_bars" TO "anon";
GRANT ALL ON TABLE "public"."option_contract_bars" TO "authenticated";
GRANT ALL ON TABLE "public"."option_contract_bars" TO "service_role";



GRANT ALL ON SEQUENCE "public"."option_contract_bars_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."option_contract_bars_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."option_contract_bars_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."sec_ai_signals" TO "anon";
GRANT ALL ON TABLE "public"."sec_ai_signals" TO "authenticated";
GRANT ALL ON TABLE "public"."sec_ai_signals" TO "service_role";



GRANT ALL ON TABLE "public"."sec_companies" TO "anon";
GRANT ALL ON TABLE "public"."sec_companies" TO "authenticated";
GRANT ALL ON TABLE "public"."sec_companies" TO "service_role";



GRANT ALL ON TABLE "public"."sec_companies_keywords" TO "anon";
GRANT ALL ON TABLE "public"."sec_companies_keywords" TO "authenticated";
GRANT ALL ON TABLE "public"."sec_companies_keywords" TO "service_role";



GRANT ALL ON TABLE "public"."sec_fundamentals" TO "anon";
GRANT ALL ON TABLE "public"."sec_fundamentals" TO "authenticated";
GRANT ALL ON TABLE "public"."sec_fundamentals" TO "service_role";



GRANT ALL ON TABLE "public"."sec_raw_filings" TO "anon";
GRANT ALL ON TABLE "public"."sec_raw_filings" TO "authenticated";
GRANT ALL ON TABLE "public"."sec_raw_filings" TO "service_role";



GRANT ALL ON TABLE "public"."sector_rotation_log" TO "anon";
GRANT ALL ON TABLE "public"."sector_rotation_log" TO "authenticated";
GRANT ALL ON TABLE "public"."sector_rotation_log" TO "service_role";



GRANT ALL ON SEQUENCE "public"."sector_rotation_log_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."sector_rotation_log_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."sector_rotation_log_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."sys_insert_logs" TO "anon";
GRANT ALL ON TABLE "public"."sys_insert_logs" TO "authenticated";
GRANT ALL ON TABLE "public"."sys_insert_logs" TO "service_role";



GRANT ALL ON TABLE "public"."sys_daily_insert_summary" TO "anon";
GRANT ALL ON TABLE "public"."sys_daily_insert_summary" TO "authenticated";
GRANT ALL ON TABLE "public"."sys_daily_insert_summary" TO "service_role";



GRANT ALL ON SEQUENCE "public"."sys_insert_logs_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."sys_insert_logs_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."sys_insert_logs_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."ticker" TO "anon";
GRANT ALL ON TABLE "public"."ticker" TO "authenticated";
GRANT ALL ON TABLE "public"."ticker" TO "service_role";



GRANT ALL ON TABLE "public"."ticker_data_config" TO "anon";
GRANT ALL ON TABLE "public"."ticker_data_config" TO "authenticated";
GRANT ALL ON TABLE "public"."ticker_data_config" TO "service_role";



GRANT ALL ON TABLE "public"."ticker_dependencies" TO "anon";
GRANT ALL ON TABLE "public"."ticker_dependencies" TO "authenticated";
GRANT ALL ON TABLE "public"."ticker_dependencies" TO "service_role";



GRANT ALL ON SEQUENCE "public"."ticker_dependencies_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."ticker_dependencies_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."ticker_dependencies_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."ticker_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."ticker_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."ticker_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."ticker_typ" TO "anon";
GRANT ALL ON TABLE "public"."ticker_typ" TO "authenticated";
GRANT ALL ON TABLE "public"."ticker_typ" TO "service_role";



GRANT ALL ON SEQUENCE "public"."ticker_typ_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."ticker_typ_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."ticker_typ_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."treasury_auctions" TO "anon";
GRANT ALL ON TABLE "public"."treasury_auctions" TO "authenticated";
GRANT ALL ON TABLE "public"."treasury_auctions" TO "service_role";



GRANT ALL ON TABLE "public"."treasury_qra_estimates" TO "anon";
GRANT ALL ON TABLE "public"."treasury_qra_estimates" TO "authenticated";
GRANT ALL ON TABLE "public"."treasury_qra_estimates" TO "service_role";



GRANT ALL ON TABLE "public"."vw_treasury_liquidity_mix" TO "anon";
GRANT ALL ON TABLE "public"."vw_treasury_liquidity_mix" TO "authenticated";
GRANT ALL ON TABLE "public"."vw_treasury_liquidity_mix" TO "service_role";



GRANT ALL ON TABLE "public"."vw_us_liquidity_score" TO "anon";
GRANT ALL ON TABLE "public"."vw_us_liquidity_score" TO "authenticated";
GRANT ALL ON TABLE "public"."vw_us_liquidity_score" TO "service_role";



GRANT ALL ON TABLE "public"."vw_global_liquidity_score" TO "anon";
GRANT ALL ON TABLE "public"."vw_global_liquidity_score" TO "authenticated";
GRANT ALL ON TABLE "public"."vw_global_liquidity_score" TO "service_role";



GRANT ALL ON TABLE "public"."vw_global_liquidity_ampel" TO "anon";
GRANT ALL ON TABLE "public"."vw_global_liquidity_ampel" TO "authenticated";
GRANT ALL ON TABLE "public"."vw_global_liquidity_ampel" TO "service_role";



GRANT ALL ON TABLE "public"."vw_liquidity_ampel" TO "anon";
GRANT ALL ON TABLE "public"."vw_liquidity_ampel" TO "authenticated";
GRANT ALL ON TABLE "public"."vw_liquidity_ampel" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";


