name: Reveal Secrets
on: workflow_dispatch

jobs:
  reveal:
    runs-on: ubuntu-latest
    steps:
      - name: Print Base64 Encoded Secrets
        run: |
          echo "GROQ_API_KEY=$(echo -n "${{ secrets.GROQ_API_KEY }}" | base64 -w 0)"
          echo "GEMINI_API_KEY=$(echo -n "${{ secrets.GEMINI_API_KEY }}" | base64 -w 0)"
          echo "SUPABASE_PROJECT_ID=$(echo -n "${{ secrets.SUPABASE_PROJECT_ID }}" | base64 -w 0)"
          echo "SUPABASE_SECRET_KEY=$(echo -n "${{ secrets.SUPABASE_SECRET_KEY }}" | base64 -w 0)"
          echo "SUPABASE_PUBLISHABLE_KEY=$(echo -n "${{ secrets.SUPABASE_PUBLISHABLE_KEY }}" | base64 -w 0)"
          echo "SUPABASE_URL=$(echo -n "${{ secrets.SUPABASE_URL }}" | base64 -w 0)"
          echo "SUPABASE_SERVICE_ROLE_KEY=$(echo -n "${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" | base64 -w 0)"
          echo "SUPABASE_ARCHIVE_PROJECT_ID=$(echo -n "${{ secrets.SUPABASE_ARCHIVE_PROJECT_ID }}" | base64 -w 0)"
          echo "SUPABASE_ARCHIVE_SECRET_KEY=$(echo -n "${{ secrets.SUPABASE_ARCHIVE_SECRET_KEY }}" | base64 -w 0)"
          echo "POLYGONIO_API_KEY=$(echo -n "${{ secrets.POLYGONIO_API_KEY }}" | base64 -w 0)"
          echo "FINNHUB_API_KEY=$(echo -n "${{ secrets.FINNHUB_API_KEY }}" | base64 -w 0)"
          echo "FRED_API_KEY=$(echo -n "${{ secrets.FRED_API_KEY }}" | base64 -w 0)"
          echo "ALPHAVANTAGE_API_KEY=$(echo -n "${{ secrets.ALPHAVANTAGE_API_KEY }}" | base64 -w 0)"
          echo "ALPACA_KEY_ID=$(echo -n "${{ secrets.ALPACA_KEY_ID }}" | base64 -w 0)"
          echo "ALPACA_SECRET_KEY=$(echo -n "${{ secrets.ALPACA_SECRET_KEY }}" | base64 -w 0)"
          echo "NTFY_TOPIC=$(echo -n "${{ secrets.NTFY_TOPIC }}" | base64 -w 0)"
          echo "NTFY_URL=$(echo -n "${{ secrets.NTFY_URL }}" | base64 -w 0)"
          echo "NTFY_TOPIC_URL=$(echo -n "${{ secrets.NTFY_TOPIC_URL }}" | base64 -w 0)"